### PR TITLE
Automation of BUG-1798719

### PR DESCRIPTION
**Pull request by yogesh-mane**
Creating user with name having more than 37 letters & mount kcephfs

bz link: https://bugzilla.redhat.com/show_bug.cgi?id=1798719

### CODE REVIEW

**Comment by rakeshgm** [comment]
@yogesh-mane PR Validation Tests Failed, please check and correct them check Travis-CI results.

**Comment by XDsubhash** [comment]
@yogesh-mane point the bz link , write some description on what it does.

how will the script run without adding it to any of the suites of nautilus or luminous?

**Comment by yogesh-mane** [comment]
luminous run logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1585553704561/
nautilus run logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1585561894427/

**Comment by XDsubhash** [comment]
PR Validation Tests still Failing, please check and correct them check Travis-CI results.

**Comment by yogesh-mane** [comment]
@XDsubhash  will add logs for each suites by tommorow

**Comment by yogesh-mane** [comment]
luminous logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1585719870705/
nautilus logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1585732967420/

**Comment by XDsubhash** [comment]
@yogesh-mane if you are done making changes ..can you reply to "requested changes part"

**Comment by yogesh-mane** [comment]
@XDsubhash , thanks for reminding me , forgot to do that.

**Pull request merged**
