### PR TITLE
Bare metal fix- Reduced the OSDs to 10

### PR DESCRIPTION
**Pull request by SrinivasaBharath**
#  Parameter verification of OSD list to 10.
 Parameters are verified on all OSDs. In some cases on bare metal, the OSD count is more. It is more than 100, so executing the test case takes more than a day. As a fix, I am picking a random 10 OSDs from the cluster.

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of the Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by SrinivasaBharath** [comment]
Pass Log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-9FXPA7

**Comment by pdhiran** [comment]
Even on a VM, with limited number of OSDs in the cluster, the param check test took 2 hours , 48 minutes. I deem this as well as too much time spent in param checking.

Can we do one OSD per host and check param on the selected host?

The code looks good!

**Comment by SrinivasaBharath** [comment]
> Even on a VM, with limited number of OSDs in the cluster, the param check test took 2 hours , 48 minutes. I deem this as well as too much time spent in param checking.
> 
> Can we do one OSD per host and check param on the selected host?
> 
> The code looks good!

The logic is changed as -
1. Select a single OSD from the host OSDs list
2. If the hosts are more than 10 then the maximum number of OSDs picked from the list is 10(logic is same)

Pass Log:    http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-MNEVCG


--

**Review by pdhiran — APPROVED** [review]
Looks good.

**Pull request merged**
