### PR TITLE
Proper 'Red Hat'

### PR DESCRIPTION
**Pull request by mykaul**
# Description

See above.

### CODE REVIEW

**Comment by ebenahar** [comment]
@mykaul is the intention to include the above checklist in ocs-ci docs? or is it to include the checklist as a template for every
PR that adds new test case/s?

**Comment by mykaul** [comment]
> @mykaul is the intention to include the above checklist in ocs-ci docs? or is it to include the checklist as a template for every
> PR that adds new test case/s?

I have no idea - I did not add this template, I just fixed the 'Redhat' to 'Red Hat' ...

**Comment by ebenahar** [comment]
Just realized it is cephci and not ocs-ci :) sorry

**Comment by psathyan** [comment]
@mykaul Thanks for spotting the incorrect usage. If you could sign your commit, I would be happy to merge it.

**Comment by mykaul** [comment]
> @mykaul Thanks for spotting the incorrect usage. If you could sign your commit, I would be happy to merge it.

I have no idea how (I did it via direct edit in github...)

**Review by veera-raghava-reddy — APPROVED** [review]

**Pull request merged**
