### PR TITLE
[NFS-Ganesha]Add failover testcase

### PR DESCRIPTION
**Pull request by MohitBis**
[NFS-Ganesha]Add failover testcase

Scenario:
1. Perform failover and delete the files from Client 2 and when primary nodes come up check the files are deleted from client 2
2. Perform failover and modify the content of file1 and when primary node come up check if the file is modified

### CODE REVIEW

**Comment by MohitBis** [comment]
Logs :
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-7IA75V/Nfs-Ganesha-HA_perform_failover_and_delete_the_files_0.log
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-NRJB86/Nfs-Ganesha-HA_perform_failover_and_modify_the_files_0.log

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by msainiRedhat — APPROVED** [review]
LGTM

**Review by vdas-redhat — APPROVED** [review]
LGTM

**Pull request merged**
