### PR TITLE
[Squid][SMB][Automation]File Operations

### PR DESCRIPTION
**Pull request by MohitBis**
[Squid][SMB][Automation]File Operations

Scenario1: Create files on windows client 1 and perform file rename from windows client 2
Scenario2: Create files on windows client 1 and delete from window client 2

### CODE REVIEW

**Comment by MohitBis** [comment]
Log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-WU24HD/

**Review by adityaramteke — APPROVED** [review]
LGTM

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by vdas-redhat — APPROVED** [review]
LGTM

**Pull request merged**
