### PR TITLE
[Nfs-Ganesha][Automation][Scenario] setuid bit

### PR DESCRIPTION
**Pull request by MohitBis**
[Nfs-Ganesha][Automation][Scenario] setuid bit

### CODE REVIEW

**Comment by MohitBis** [comment]
Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-BFMA7N/Nfs_Verify_setuid_bit_set_on_a_file_0.log

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by msainiRedhat — DISMISSED** [review]
LGTM

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by msainiRedhat — APPROVED** [review]
LGTM

**Review by tintumathew10 — APPROVED** [review]
LGTM

**Pull request merged**
