### PR TITLE
Fix for the podman pull registry issue

### PR DESCRIPTION
**Pull request by tintumathew10**
# Description

Fix for podman pull registry issue.

[cephci-run-FLYID7.zip](https://github.com/red-hat-storage/cephci/files/12879826/cephci-run-FLYID7.zip)

### CODE REVIEW

**Comment by tintumathew10** [comment]
2023-10-12 14:48:18,084 (cephci.test_cephadm) [INFO] - cephci.ceph.ceph.py:1558 - Running command cephadm --image registry-proxy.engineering.redhat.com/rh-osbs/rhceph:ceph-7.0-rhel-9-containers-candidate-21795-20231011192839 bootstrap --mon-ip 10.0.209.116 on 10.0.209.116 timeout 1800
2023-10-12 14:49:18,475 (cephci.test_cephadm) [INFO] - cephci.ceph.ceph.py:1592 - Command completed successfully
2023-10-12 14:49:18,476 (cephci.test_cephadm) [INFO] - cephci.ceph.ceph_admin.bootstrap.py:327 - Bootstrap output : Creating directory /etc/ceph for ceph.conf
Verifying podman|docker is present...
Verifying lvm2 is present...
Verifying time synchronization is in place...
Unit chronyd.service is enabled and running
Repeating the final host check...
podman (/usr/bin/podman) version 4.4.1 is present
systemctl is present
lvcreate is present
Unit chronyd.service is enabled and running
Host looks OK
Cluster fsid: 48304a7c-68e0-11ee-ac85-fa163e306a86
Verifying IP 10.0.209.116 port 3300 ...
Verifying IP 10.0.209.116 port 6789 ...
Mon IP `10.0.209.116` is in CIDR network `10.0.208.0/22`
Mon IP `10.0.209.116` is in CIDR network `10.0.208.0/22`
Internal network (--cluster-network) has not been provided, OSD replication will default to the public_network
Pulling container image registry-proxy.engineering.redhat.com/rh-osbs/rhceph:ceph-7.0-rhel-9-containers-candidate-21795-20231011192839...
Ceph version: ceph version 18.2.0-86.el9cp (fd0956847f66c98c9c4a45f39e86ff6922a47262) reef (stable)
Extracting ceph user uid/gid from container image...
Creating initial keys...
Creating initial monmap...
Creating mon...
Waiting for mon to start...
Waiting for mon...
mon is available
Assimilating anything we can from ceph.conf...
Generating new minimal ceph.conf...
Restarting the monitor...
Setting mon public_network to 10.0.208.0/22
Wrote config to /etc/ceph/ceph.conf
Wrote keyring to /etc/ceph/ceph.client.admin.keyring
Creating mgr...
Verifying port 0.0.0.0:9283 ...
Verifying port 0.0.0.0:8765 ...
Verifying port 0.0.0.0:8443 ...
Waiting for mgr to start...
Waiting for mgr...
mgr not available, waiting (1/15)...
mgr not available, waiting (2/15)...
mgr not available, waiting (3/15)...
mgr is available
Enabling cephadm module...
Waiting for the mgr to restart...
Waiting for mgr epoch 5...
mgr epoch 5 is available
Setting orchestrator backend to cephadm...
Generating ssh key...
Wrote public SSH key to /etc/ceph/ceph.pub
Adding key to root@localhost authorized_keys...
Adding host ceph-tm1-70-test-flyid7-node1-installer...
Deploying mon service with default placement...
Deploying mgr service with default placement...
Deploying crash service with default placement...
Deploying ceph-exporter service with default placement...
Deploying prometheus service with default placement...
Deploying grafana service with default placement...
Deploying node-exporter service with default placement...
Deploying alertmanager service with default placement...
Enabling the dashboard module...
Waiting for the mgr to restart...
Waiting for mgr epoch 9...
mgr epoch 9 is available
Generating a dashboard self-signed certificate...
Creating initial admin user...
Fetching dashboard port number...
Ceph Dashboard is now available at:

	     URL: https://ceph-tm1-70-test-flyid7-node1-installer:8443/
	    User: admin
	Password: dunvvv9unj

Enabling client.admin keyring and conf on hosts with "admin" label
Saving cluster configuration to /var/lib/ceph/48304a7c-68e0-11ee-ac85-fa163e306a86/config directory
Skipping call home integration. --enable-ibm-call-home not provided
Enabling autotune for osd_memory_target
You can access the Ceph CLI as following in case of multi-cluster or non-default config:

	sudo /usr/sbin/cephadm shell --fsid 48304a7c-68e0-11ee-ac85-fa163e306a86 -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring

Or, if you are only running a single cluster on this host:

	sudo /usr/sbin/cephadm shell 

Please consider enabling telemetry to help improve Ceph:

	ceph telemetry on

For more information see:

	https://docs.ceph.com/en/latest/mgr/telemetry/

Bootstrap complete.

**Comment by tintumathew10** [comment]
image

**Review by vamahaja — COMMENTED** [review]
LGTM

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by MohitBis — APPROVED** [review]
LGTM

**Review by vamahaja — APPROVED** [review]

**Pull request merged**
