### PR TITLE
Integrated all supported RGW compression types in cephci

### PR DESCRIPTION
**Pull request by udaysk23**
Integrated all supported RGW compression types in cephci

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by udaysk23** [comment]
Following is the log location of successful 4.x run:
https://ceph-downstream-jenkins-csb-storage.apps.ocp-c1.prod.psi.redhat.com/job/rhceph-test-executor/687/console

**Review by viduship — COMMENTED** [review]
looks good

**Review by ckulal — APPROVED** [review]

**Review by anrao19 — APPROVED** [review]
LGTM

**Comment by udaysk23** [comment]
Following is the log location of successful 5.x run:
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-LD1KY0

**Review by mkasturi18 — APPROVED** [review]

**Pull request merged**
