### PR TITLE
Container upgrade  from 3.3-Rhel 7.8 to 4.1-Rhel7.8

### PR DESCRIPTION
**Pull request by SrinivasaBharath**
Ceph Container rolling upgrade from 3.3-rhel-7.8 to 4.1-rhel-7.8

### CODE REVIEW

**Comment by XDsubhash** [comment]
can you provide the cli to use to run this upgrade?And also post the succesful run logs link

**Comment by rakeshgm** [comment]
@SrinivasaBharath Good one.

**Comment by rakeshgm** [comment]
Could you please sign your commits, and also add a small brief in the description section.

**Comment by SrinivasaBharath** [comment]
CLI - python3 run.py --rhbuild 3.3-rhel-7 --global-conf conf/nautilus/upgrades/upgrade_3.x_to_4.x.yaml --osp-cred osp/osp-cred-ci-2.yaml --inventory conf/inventory/rhel-7.8-server-x86_64.yaml --suite suites/nautilus/upgrades/upgrade_container_3.x_to_4.x.yaml --log-level info --store

Log Location - ERROR:No latest nightly container UMB msg at /ceph/cephci-jenkins/latest-rhceph-container-info/,specify using the cli args or use --ignore-latest-container
Root Cause for the issue- In utility.utils.py file the method "get_latest_container"  method gets the docker deatils from the url "'http://magna002.ceph.redhat.com/cephci-jenkins/latest-rhceph-container-info/latest-RHCEPH-3.3-rhel-7.json" This path not exist at the location. instead of this "http://magna002.ceph.redhat.com/cephci-jenkins/latest-rhceph-container-info/latest-RHCEPH-3.3.json" exist.

Proper naming convention not followed compare with other builds.Screen shot attached.
image (1)

**Comment by XDsubhash** [comment]
1) there is no 3.3-rhel-7 repos in rhbuild.yaml https://github.com/red-hat-storage/cephci/blob/master/rhbuild.yaml#L9 to use 

2) if upgrading from n-1 to n (eg: 3.x to 4.x  the rhbuild paramter should be pointing to n )thats how its done here #101

**Comment by XDsubhash** [comment]
@SrinivasaBharath can you open for review if the pr is ready? or close it and send a new one

**Comment by rakeshgm** [comment]
@SrinivasaBharath and @XDsubhash can this be closed. since there has been no update on this for quite some time.

**Comment by SrinivasaBharath** [comment]
Hi Rakesh,

    we can close this  as I am not working on this task.

Regards,
Bharath

**Pull request closed without merging**
