### PR TITLE
Adds support of providing custom IP for MON deployment

### PR DESCRIPTION
**Pull request by udaysk23**
# Description
Adds support of providing custom IP for MON deployment

Eg:
  - test:
      abort-on-fail: true
      config:
            verify_cluster_health: true
            steps:
              - config:
                  command: bootstrap
                  service: cephadm
                  args:
                    mon-ip: 123.23.45.136
                    allow-fqdn-hostname: true
                    orphan-initial-daemons: true
                    initial-dashboard-password: admin@123
                    dashboard-password-noupdate: true
                    cluster-network: 123.24.0.0/16

Pass log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-SU9BJN/
Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by mkasturi18 — COMMENTED** [review]
Changes look good to me.

**Comment by AmarnatReddy** [comment]
Hi @udaysk23,
for mon-ip: if you specify the node id it will get the IP address from the node only.
we usually follow **node-id** as value for mon-ip.
Is the interface different from what we provide in conf file?
mon-ip will be taken from conf file only which we give in host details
sample : 
        -
          hostname: cali020
          id: node9
          **ip: 10.8.130.20**
          root_password: passwd
          role:
            - osd

**Comment by udaysk23** [comment]
> Hi @udaysk23, for mon-ip: if you specify the node id it will get the IP address from the node only. we usually follow **node-id** as value for mon-ip. Is the interface different from what we provide in conf file? mon-ip will be taken from conf file only which we give in host details sample : - hostname: cali020 id: node9 **ip: 10.8.130.20** root_password: passwd role: - osd

@AmarnatReddy There are some cases like DFG where we need to provide different MON IP which is Private IP and not pingable outside of that lab environment which we cant provide in conf file due to connectivity issue.

**Comment by mkasturi18** [comment]
@udaysk23 , there is a review comment, could you please address it

**Comment by mkasturi18** [comment]
@udaysk23 , Remainder! to address the review comments..

**Comment by udaysk23** [comment]
> @udaysk23 , Remainder! to address the review comments..

@mkasturi18 I have already addressed review comment on July 11. Kindly re-review the code

**Comment by mkasturi18** [comment]
@AmarnatReddy , could you please look at the review comment. Are we good to merge the fix?

**Pull request closed without merging**
