### PR TITLE
[Squid][SMB][Automation]Add failover scenarios

### PR DESCRIPTION
**Pull request by MohitBis**
[Squid][SMB][Automation]Add failover scenarios
Scenarios:
1. (Clustering - Failover-Maintenance Mode)Verify samba failover with parallel IOs
2. (Clustering - Failover-Restart Service)Verify samba failover with parallel IOs
3. (Clustering - Failover-Reboot)Verify samba failover with parallel IOs
4. (Clustering - Failover-Stop Service)Verify samba failover with parallel IOs
5. (Clustering - Failover-Kill Service)Verify samba failover with parallel IOs

### CODE REVIEW

**Comment by MohitBis** [comment]
Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-M3YP3R/

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by adityaramteke — APPROVED** [review]
LGTM

**Review by tintumathew10 — APPROVED** [review]
lgtm

**Pull request merged**
