### PR TITLE
[Rados-RGW] RGW multisite erasure-code-profile pool suite with bilog trim testcase

### PR DESCRIPTION
**Pull request by anrao19**
# Description
suite included as per the requirement in:  https://issues.redhat.com/browse/RHCEPHQE-15945

RGW multisite suite  with 
1. erasure-code-profile pool
2. bilog trim testcase

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by harshkumarRH — APPROVED** [review]
Looks good! Thanks @anrao19

**Comment by harshkumarRH** [comment]
@mkasturi18 @anrao19 We can merge this PR if there are no additional reviews pending

**Comment by mkasturi18** [comment]
@harshkumarRH , The PR doesnot include any testcases from Rados. Do you want the PR to be merged and later you add your testcases?

**Comment by harshkumarRH** [comment]
> @harshkumarRH , The PR doesnot include any testcases from Rados. Do you want the PR to be merged and later you add your testcases?

@mkasturi18 yes, I will add relevant RADOS test cases to the same test suite

**Comment by mkasturi18** [comment]
Merging the PR based on above comment

**Review by mkasturi18 — APPROVED** [review]

**Pull request merged**
