### PR TITLE
OSD- failure tc fix

### PR DESCRIPTION
**Pull request by yogesh-mane**
# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs

# Checklist:

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test

Adding delay for cluster to come back in health_ok state
Adding py3 installation for rhel 7

### CODE REVIEW

**Comment by yogesh-mane** [comment]
This PR solves osds down issue after OSD-failure tc

**Comment by yogesh-mane** [comment]
rhel 7 logs = http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1603298849535
(suite is skipping 'MDS-pinning-system_tests' tc as it's getting stuck for network issue)

**Comment by yogesh-mane** [comment]
running suite for rhel-8-4.2

**Comment by yogesh-mane** [comment]
Hi
I rebased fs_py3_changes branch with master branch.
I think other commits are from master branch itself.
Let me know if I should submit my changes only.

**Comment by yogesh-mane** [comment]
4.2-rhel-8 logs = http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-160334764374

**Comment by rakeshgm** [comment]
@yogesh-mane rebase needed.

**Comment by yogesh-mane** [comment]
@rakeshgm , it is already rebased. any other changes needed?

**Comment by rakeshgm** [comment]
> @rakeshgm , it is already rebased. any other changes needed?

Have you looked at the number of commits.

**Comment by yogesh-mane** [comment]
> Have you looked at the number of commits.

Sorry for misunderstanding. I thought you were referring to this comment
>@yogesh-mane rebase needed.

when you said you have added the comments for PR in chat.
Take your time for reviewing the commits.

**Comment by yogesh-mane** [comment]
Closing this PR due to conflicts. I have created new PR for this issue -  https://github.com/red-hat-storage/cephci/pull/268

**Pull request closed without merging**
