### PR TITLE
updated conf path in rgw squid suites

### PR DESCRIPTION
**Pull request by yuva-gayam**
# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>
This metadata file is referenced for making changes to RGW configuration.
[metadata link](https://gitlab.cee.redhat.com/rhcs-qe/cephqe-jenkins/-/blob/main/metadata/squid/rgw.yaml)

### CODE REVIEW

**Comment by ckulal** [comment]
please look into the jenkin check failure

**Comment by yuva-gayam** [comment]
Fixed Jenkins failure. @ckulal , @anrao19  - please review this PR.

**Review by ckulal — APPROVED** [review]

**Pull request merged**
