### PR TITLE
[Utility] Add support vault server in config

### PR DESCRIPTION
**Pull request by vamahaja**
Add support fot vault server configuration

### CODE REVIEW

**Review by tintumathew10 — COMMENTED** [review]
LGTM

**Comment by vamahaja** [comment]
@viduship @mkasturi18 please review

**Review by viduship — COMMENTED** [review]
can we have a pass log with these changes?

**Comment by vamahaja** [comment]
@viduship this is simple library which can be used in the test workflows to get the vault server details. Unit testing completed.

**Comment by vamahaja** [comment]
Here are the test details

Config:
```
$ cat ~/.cephci.yaml
credentials:
    vault:
      url: fake-url
      agent:
        auth: fake-auth
        engine: fake-engine
        role-id: fake-role-id
        secret-id: fake-secret-id
        prefix: fake-prefix
```

Testcase :
```
$ cat test-vault-config.py 
from cephci.utils.configs import get_configs, get_vault_credentials

# Read configuration for cloud
get_configs()

# Get vault server configs
vault_server = get_vault_credentials()

# stdout vault server details
```

Results -
```
$ python test-vault-config.py 
2023-08-16 11:29:11,778 (cephci.cephci.utils.configs) [INFO] - cephci.cephci.cephci.utils.configs.py:27 - Loading config file - /home/vamahaja/.cephci.yaml
2023-08-16 11:29:11,782 (cephci.cephci.utils.configs) [INFO] - cephci.cephci.cephci.utils.configs.py:127 - Loading cloud credentials for vault server
{'url': 'fake-url', 'agent': {'auth': 'fake-auth', 'engine': 'fake-engine', 'role-id': 'fake-role-id', 'secret-id': 'fake-secret-id', 'prefix': 'fake-prefix'}}
```

**Review by viduship — APPROVED** [review]
Approving the PR based on the functionality.

**Pull request merged**
