### PR TITLE
[NFS-Ganesha][Reef][Upgrade]update upgrade suite

### PR DESCRIPTION
**Pull request by MohitBis**
[NFS-Ganesha][Reef][Upgrade]update upgrade suite

Added NFS-Ganesha cluster setup before upgrade and NFS-Ganesha IO while upgrade

### CODE REVIEW

**Comment by MohitBis** [comment]
Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-9DKTNK/

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by msainiRedhat — APPROVED** [review]
LGTM

**Review by vdas-redhat — APPROVED** [review]
LGTM

**Pull request merged**
