### PR TITLE
Removed the tests which are taking more execution time

### PR DESCRIPTION
**Pull request by SrinivasaBharath**
# Description
In the regression suite, few test execution is taking execution time. Due to this, the execution of the regression suite is taking more than 5 hours. From the results summary, the team noticed that the following suites are taking more execution time.
Test cases:
1.CEPH-83571670
2. CEPH-83573854
3. CEPH-83571671

This PR is to remove the test cases for the regression suite.

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by pdhiran** [comment]
Remove the tests from all pacific, Quincy and reef suites.

The removed tests can be added in tier4_rados_tests.

**Review by pdhiran — COMMENTED** [review]
Changes look good. Please add the pass logs.

**Comment by SrinivasaBharath** [comment]
Pass Log for the regression  - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-T3CWIQ

**Comment by SrinivasaBharath** [comment]
CEPH-83571670 and CEPH-83573854 test cases failed due to the re_pool_compress pool not existing in the cluster.
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-B60O4O

**Comment by pdhiran** [comment]
Hey Bharath, to rectify the failure, can we add this to the config for the moved tests?

```
    config:
        replicated_pool:
          create: true
          pool_name: re_pool_compress
          pg_num: 32
          rados_write_duration: 10
          rados_read_duration: 10 
```

Execution time looks well within the permitted limits.

**Comment by SrinivasaBharath** [comment]
suites/quincy/rados/tier-4_rados_tests.yaml  suite execution log .
Log file - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-FGXCSC

**Comment by SrinivasaBharath** [comment]
> Hey Bharath, to rectify the failure, can we add this to the config for the moved tests?
> 
> ```
>     config:
>         replicated_pool:
>           create: true
>           pool_name: re_pool_compress
>           pg_num: 32
>           rados_write_duration: 10
>           rados_read_duration: 10 
> ```
> 
> Execution time looks well within the permitted limits.

Done

**Review by pdhiran — APPROVED** [review]
Looks Good. Please update the ticket with run duration.

**Pull request merged**
