### PR TITLE
IO Perf Test

### PR DESCRIPTION
**Pull request by sunilkumarn417**
- Improvised run_fio method to execute with more options.
- Execute IO via libRBD and NVMeoF protocols and collect the data artifacts.
- Generate CSV and JSON result files from the test run.
- Plot charts on every important metirc from the execution to compare the performance between LibRBD vs NVMeOF.
- Modified cleanup/teardown to work as separate test.
 - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-Y19BBH/
```
   # Cleanup Test Case
  - test:
      abort-on-fail: true
      config:
        gw_node: node6
        rbd_pool: rbd
        do_not_create_image: true
        rep-pool-only: true
        rep_pool_config:
        subsystems:
          - nqn: nqn.2016-06.io.spdk:cnode1
        initiators:
          - subnqn: nqn.2016-06.io.spdk:cnode1
            node: node7
        cleanup-only: true                        # clean up only
        cleanup:
          - pool
          - subsystems
          - initiators
          - gateway
      desc: Clean up the nvme-of target entities subsystem, Initiator, gateway
      destroy-cluster: false
      module: test_ceph_nvmeof_gateway.py
      name: Cleanup the nvme-of Gateway entities 
```

**Results:**
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-JHMRFG/(latest)

**Chart example:**
image

**Artifacts:**
image

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-MEBIFG/Perf_test_with_10Gb_with_4kb_block_size_0.log
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-IJBXWV/
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-7OZY29/Perf_test_with_10Gb_with_4kb_block_size_0.log

### CODE REVIEW

**Review by rahullepakshi — DISMISSED** [review]
LGTM

**Review by preethisn — DISMISSED** [review]
LGTM

**Comment by sunilkumarn417** [comment]
**latest result:**
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-MEBIFG/Perf_test_with_10Gb_with_4kb_block_size_0.log
```

2023-07-02 23:46:45,596 (cephci.test_io_perf) [INFO] - cephci.tests.rbd.rbd_utils.py:105 - Command execution complete
{'FIO_WRITE_BS_4k_IODepth8_LIBAIO-1NJI-0-librbd': {'name': 'FIO_WRITE_BS_4k_IODepth8_LIBAIO', 'protocol': 'librbd', 'io_type': 'write', 'io_information': {'ioengine': 'libaio', 'filename': '/dev/rbd0', 'size': '100%', 'name': 'FIO_WRITE_BS_4k_IODepth8_LIBAIO-1NJI-0-librbd', 'numjobs': '1', 'rw': 'write', 'iodepth': '8', 'fsync': '32'}, 'write': {'iops': 5307.514917, 'bw': 21242.424519, 'slat_ns': 5451.916256, 'clat_ns': 1320319.381906, 'lat_ns': 1325943.08035}}, 'FIO_READ_BS_4k_IODepth8_LIBAIO-1NJI-0-librbd': {'name': 'FIO_READ_BS_4k_IODepth8_LIBAIO', 'protocol': 'librbd', 'io_type': 'read', 'io_information': {'ioengine': 'libaio', 'filename': '/dev/rbd0', 'runtime': '120', 'name': 'FIO_READ_BS_4k_IODepth8_LIBAIO-1NJI-0-librbd', 'numjobs': '1', 'rw': 'read', 'iodepth': '8', 'fsync': '32'}, 'read': {'iops': 28355.760737, 'bw': 114456.405063, 'slat_ns': 32878.873356, 'clat_ns': 248241.629711, 'lat_ns': 281228.774967}}, 'FIO_WRITE_BS_4k_IODepth8_LIBAIO-XQFC-0-nvmeof': {'name': 'FIO_WRITE_BS_4k_IODepth8_LIBAIO', 'protocol': 'nvmeof', 'io_type': 'write', 'io_information': {'ioengine': 'libaio', 'filename': '/dev/nvme0n1', 'size': '100%', 'name': 'FIO_WRITE_BS_4k_IODepth8_LIBAIO-XQFC-0-nvmeof', 'numjobs': '1', 'rw': 'write', 'iodepth': '8', 'fsync': '32'}, 'write': {'iops': 4106.548697, 'bw': 16434.903605, 'slat_ns': 5611.244656, 'clat_ns': 1706073.344255, 'lat_ns': 1711893.56159}}, 'FIO_READ_BS_4k_IODepth8_LIBAIO-XQFC-0-nvmeof': {'name': 'FIO_READ_BS_4k_IODepth8_LIBAIO', 'protocol': 'nvmeof', 'io_type': 'read', 'io_information': {'ioengine': 'libaio', 'filename': '/dev/nvme0n1', 'runtime': '120', 'name': 'FIO_READ_BS_4k_IODepth8_LIBAIO-XQFC-0-nvmeof', 'numjobs': '1', 'rw': 'read', 'iodepth': '8', 'fsync': '32'}, 'read': {'iops': 27800.573314, 'bw': 112210.329114, 'slat_ns': 33395.271858, 'clat_ns': 253298.598257, 'lat_ns': 286800.13476}}}
name,protocol,io_type,read_iops,read_bandwidth,read_slat_avg_ns,read_clat_avg_ns,read_lat_avg_ns,write_iops,write_bandwidth,write_slat_avg_ns,write_clat_avg_ns,write_lat_avg_ns
FIO_WRITE_BS_4k_IODepth8_LIBAIO,librbd,write,,,,,,5307.514917,21242.424519,5451.916256,1320319.381906,1325943.08035
FIO_READ_BS_4k_IODepth8_LIBAIO,librbd,read,28355.760737,114456.405063,32878.873356,248241.629711,281228.774967
FIO_WRITE_BS_4k_IODepth8_LIBAIO,nvmeof,write,,,,,,4106.548697,16434.903605,5611.244656,1706073.344255,1711893.56159
FIO_READ_BS_4k_IODepth8_LIBAIO,nvmeof,read,27800.573314,112210.329114,33395.271858,253298.598257,286800.13476
```

**Review by Manohar-Murthy — APPROVED** [review]
group review is done.merging.

**Pull request merged**
