### PR TITLE
Integrated cloud transition basic workflow test

### PR DESCRIPTION
**Pull request by vivekanandan-k-rh**
# Description

Integrated cloud transition basic workflow test

Passed log: http://magna002.ceph.redhat.com/ceph-qe-logs/vivekanandan/cephci-run-PS6KQC/

### CODE REVIEW

**Review by udaysk23 — DISMISSED** [review]

**Review by anrao19 — APPROVED** [review]

**Comment by mkasturi18** [comment]
@vivekanandan-k-rh , the changes looks good to me. Could you also add these tests to 6.0 pipeline.

**Review by anrao19 — APPROVED** [review]

**Comment by anrao19** [comment]
@vivekanandan-k-rh  Since you have included conf for pacific and going to add it as a part of 5.3 pipeline you can add it to sanity, tier-2, stage-7

**Comment by mkasturi18** [comment]
@vivekanandan-k-rh , as cloud transition is a quincy feature, could add the conf file to quincy folder, instead of  conf/pacific/rgw/cloud_transition.yaml

**Comment by vivekanandan-k-rh** [comment]
> @vivekanandan-k-rh Since you have included conf for pacific and going to add it as a part of 5.3 pipeline you can add it to sanity, tier-2, stage-7

Done @anrao19

**Review by anrao19 — APPROVED** [review]

**Review by mkasturi18 — APPROVED** [review]

**Pull request merged**
