### PR TITLE
Added snap removal method and changes to trash command w.r.t parent image to the existing v2 clone function

### PR DESCRIPTION
**Pull request by preethisn**
changes to trash command for v2clone functionality when parent image is deleted and viewed from trash.

### CODE REVIEW

**Comment by preethisn** [comment]
new logs are attached - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-MV4QA4/

**Comment by VasishtaShastry** [comment]
@preethisn Can workflow be updated please ?

**Comment by preethisn** [comment]
> @preethisn Can workflow be updated please ? This is w.r.t to the PR 1454 with correct working steps for the v2 clone functionality. This does Verification of the deletion of parent image when clone is flattened when V2clone is enabled. We have added trash command for parent image removal and snapshot removal for the test flow to complete.

************Updated test workflow in the module

**Comment by VasishtaShastry** [comment]
Updates in doc string with workflow looks good to me.

**Review by Manohar-Murthy — APPROVED** [review]
lgtm.

**Pull request merged**
