### PR TITLE
Delete non-exist subvolume group name

### PR DESCRIPTION
**Pull request by julpark-rh**
1. Create a subvolume name that does not exist
2. Try to remove the subvolume name that does not exist
3. The command should fail because the subvolume name does not exist.
4. Check if the command is failed
   
 https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574168
 http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-7HU8LW  

Signed-off-by: julpark-rh <yonhyun@gmail.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by hkadam134** [comment]
@julpark-rh - Pre-checks have failed, can you fix and re-submit..

**Review by hkadam134 — CHANGES_REQUESTED** [review]
@julpark-rh - Pre-checks have failed, can you fix and re-submit..

**Comment by julpark-rh** [comment]
> @julpark-rh - Pre-checks have failed, can you fix and re-submit..

I have applied those changes.

**Comment by hkadam134** [comment]
@julpark-rh - Can you allign this with Tier2 suire under - tier-2_cephfs_test-volume-management.yaml.
Also change the name of the file as per the test summary.

**Review by AmarnatReddy — DISMISSED** [review]

**Comment by veera-raghava-reddy** [comment]
@julpark-rh have you incorporated the inputs form Hemanth?

**Review by hkadam134 — CHANGES_REQUESTED** [review]
@julpark-rh - Please refer this yaml and see how the tests are added - suites/pacific/cephfs/tier-2/tier-2_cephfs_test-volume-management.yaml and follow the same for other PR's also..

**Review by hkadam134 — APPROVED** [review]
Looks Good

**Review by hkadam134 — CHANGES_REQUESTED** [review]
@julpark-rh - Why don't you add these 2 tests in one PR to avoid merge conflicts..

Delete non-exist subvolume group name with force option #1086
Delete non-exist subvolume group name #1081

**Comment by julpark-rh** [comment]
> @julpark-rh - Why don't you add these 2 tests in one PR to avoid merge conflicts..
> 
> Delete non-exist subvolume group name with force option #1086 Delete non-exist subvolume group name #1081

@hkadam134 Yes I can do that. but the other PR is waiting to be merged.. is it still okay to raise combined PR now?

**Comment by hkadam134** [comment]
> > @julpark-rh - Why don't you add these 2 tests in one PR to avoid merge conflicts..
> > Delete non-exist subvolume group name with force option #1086 Delete non-exist subvolume group name #1081
> 
> @hkadam134 Yes I can do that. but the other PR is waiting to be merged.. is it still okay to raise combined PR now?

@julpark-rh - resubmit this PR as there are conflicts.

**Comment by julpark-rh** [comment]
Re- submit PR

**Pull request closed without merging**
