### PR TITLE
[Test] Validate the /crush endpoint of RESTful module

### PR DESCRIPTION
**Pull request by sayaleeraut**
# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by pranavprakash20 — APPROVED** [review]
Lgtm

**Review by vamahaja — CHANGES_REQUESTED** [review]
refer PR [1] for changes.
[1] https://github.com/red-hat-storage/cephci/pull/4059

**Review by vamahaja — COMMENTED** [review]
Change looks good, kindly share test runs results.

**Comment by sayaleeraut** [comment]
Closing this PR.

While adding changes -
% git status
On branch test_restful_crush_endpoint
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   api/restful/crush.py
	modified:   suites/squid/cephmgr/tier2-restful-endpoint-operations.yaml
	new file:   tests/mgr/test_restful_operations_crush_endpoint.py

But after committing and pushing changes, files from older commit got added as well. Will open a new PR from a new branch.

**Pull request closed without merging**
