### PR TITLE
[Squid][SMB][Automation]File Operation

### PR DESCRIPTION
**Pull request by MohitBis**
[Squid][SMB][Automation]File Operation
Create files on windows client 1 and perform lookup from windows client 2

### CODE REVIEW

**Comment by MohitBis** [comment]
Log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-9X8IXD/

**Review by adityaramteke — APPROVED** [review]
LGTM

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by tintumathew10 — APPROVED** [review]
LGTM

**Pull request merged**
