### PR TITLE
new nvmeof-cli modules

### PR DESCRIPTION
**Pull request by sunilkumarn417**
- Libs for new nvmeof-cli
-  new CLI adoption

|Test Name | Test Description | Duration | Status | Comments|
|-- | -- | -- | -- | --|
configure Ceph client for NVMe tests | Setup client on NVMEoF gateway | 0:00:23.747888 | Pass |  
deploy nvmeof gateway | NVMeoF Gateway deployment using cephadm | 0:02:21.389341 | Pass |  
Manage nvmeof gateway entities | Manage NVMeoF Subsystem entities | 0:00:29.421228 | Pass |  
Delete nvmeof gateway | NVMeoF Gateway deployment using cephadm | 0:00:25.852811 | Pass |  
Delete nvmeof gateway pre-reqs | NVMeoF Gateway deployment using cephadm | 0:00:25.853487 | Pass |  
Basic E2ETest Ceph NVMEoF GW sanity test on dedicated node | E2E-Test NVMEoF Gateway on dedicated node and Run IOs on targets | 0:17:08.717097 | Pass |  
Basic E2ETest Ceph NVMEoF GW sanity test with collocation-FIPS | E2E-Test NVMEoF Gateway collocated and Run IOs on targets | 0:17:30.427844 | Pass |  

Test Results
Test Name	Test Description	Duration	Status	Comments
[configure Ceph client for NVMe tests](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83573758)	Setup client on NVMEoF gateway	0:00:23.747888	[Pass](https://github.com/red-hat-storage/cephci/pull/configure_Ceph_client_for_NVMe_tests_0.log)	
[deploy nvmeof gateway](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=None)	NVMeoF Gateway deployment using cephadm	0:02:21.389341	[Pass](https://github.com/red-hat-storage/cephci/pull/deploy_nvmeof_gateway_0.log)	
[Manage nvmeof gateway entities](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83575783)	Manage NVMeoF Subsystem entities	0:00:29.421228	[Pass](https://github.com/red-hat-storage/cephci/pull/Manage_nvmeof_gateway_entities_0.log)	
[Delete nvmeof gateway](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=None)	NVMeoF Gateway deployment using cephadm	0:00:25.852811	[Pass](https://github.com/red-hat-storage/cephci/pull/Delete_nvmeof_gateway_0.log)	
[Delete nvmeof gateway pre-reqs](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=None)	NVMeoF Gateway deployment using cephadm	0:00:25.853487	[Pass](https://github.com/red-hat-storage/cephci/pull/Delete_nvmeof_gateway_pre-reqs_0.log)	
[Basic E2ETest Ceph NVMEoF GW sanity test on dedicated node](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83575441)	E2E-Test NVMEoF Gateway on dedicated node and Run IOs on targets	0:17:08.717097	[Pass](https://github.com/red-hat-storage/cephci/pull/Basic_E2ETest_Ceph_NVMEoF_GW_sanity_test_on_dedicated_node_0.log)	
[Basic E2ETest Ceph NVMEoF GW sanity test with collocation-FIPS](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83577610)	E2E-Test NVMEoF Gateway collocated and Run IOs on targets	0:17:30.427844	[Pass](https://github.com/red-hat-storage/cephci/pull/Basic_E2ETest_Ceph_NVMEoF_GW_sanity_test_with_collocation-FIPS_0.log)	
CLI Arguments
/home/sunilkumar/workspace/venv/bin/python3 run.py --log-level debug --osp-cred /home/sunilkumar/osp.yaml --instances-name 2sunilkumar --rhbuild 7.0 --build upstream --upstream-build reef --platform rhel-9 --global-conf conf/reef/nvmeof/ceph_nvmeof_sanity.yaml --suite suites/reef/nvmeof/tier-0_nvmeof_sanity.yaml --inventory conf/inventory/rhel-9.3-server-x86_64-large.yaml --custom-config nvmeof_cli_image=quay.io/ceph/nvmeof-cli:v0.0.7 --custom-config nvmeof_image=quay.io/ceph/nvmeof:v0.0.7 --docker-registry quay.ceph.io --docker-image ceph-ci/ceph --docker-tag 9c9b2197bb3d0836c997bf41e691c368693100be --rhs-ceph-repo https://3.chacra.ceph.com/repos/ceph/reef/9c9b2197bb3d0836c997bf41e691c368693100be/centos/9/flavors/default/repo --reuse rerun/2sunilkumar-D1E7IE

### CODE REVIEW

**Review by HaruChebrolu — DISMISSED** [review]
lgtm

**Review by HaruChebrolu — APPROVED** [review]

**Comment by sunilkumarn417** [comment]
```
All test logs located here: /tmp/cephci-run-WES99D

TEST NAME                        TEST DESCRIPTION                                               DURATION                         STATUS                    COMMENTS
Delete-recreate bdev namespace   Delete-recreate bdev in loop and rediscover namespace          0:04:15.236513                   Pass                             
Perform restart of NVMeOF gate   Perform restart and validate the gateway entities              0:04:38.896214                   Pass                             
Map-Unmap NVMe namespaces cont   Perform map and unmap NVMe namespaces in loop                  0:03:42.116119                   Pass                             
Reboot client node and check N   Perform reboot on initiator node and validate the namespaces   0:04:00.008254                   Pass                             
RBD operations shrink and expa   Perform RBD operations shrink and expand on images.            0:19:48.778071                   Failed                           
Validate Host accessibility to   Validate Host accessibility via nvme-cli commands.             0:04:38.287664                   Pass                             
Test to Deploy multiple NVMEoF   Deploy multiple NVMEoF Gateway on the cluster                  0:18:04.241250                   Pass                             
Perform cluster operations whe   Perform cluster operations when  IO operations between NVMeO   0:15:57.961838                   Pass                             
Reboot GW node and check NVMe    Perform reboot on GW node and validate the namespaces.         0:08:38.881262                   Pass                             


```

**Comment by sunilkumarn417** [comment]
```

<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Test Results</h2>
Test Name | Test Description | Duration | Status | Comments
-- | -- | -- | -- | --
RBD operations shrink and expand on images | Perform RBD operations shrink and expand on images. | 0:06:17.327449 | Pass |  

<br class="Apple-interchange-newline">Test Results
Test Name	Test Description	Duration	Status	Comments
[RBD operations shrink and expand on images](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83575813)	Perform RBD operations shrink and expand on images.	0:06:17.327449	[Pass](https://github.com/red-hat-storage/cephci/pull/RBD_operations_shrink_and_expand_on_images_0.log)
```

**Comment by sunilkumarn417** [comment]
```
All test logs located here: /tmp/cephci-run-ZE9IHO

TEST NAME                        TEST DESCRIPTION                                               DURATION                         STATUS                    COMMENTS
RBD operations shrink and expa   Perform RBD operations shrink and expand on images.            0:25:36.252147                   Pass                             

```

**Review by HaruChebrolu — APPROVED** [review]
lgtm

**Comment by sunilkumarn417** [comment]
Will CLose this PR. waiting for NVMeoF 0.0.7 downstream version.

**Pull request closed without merging**
