### PR TITLE
Align nautilus suite to upstream branch rename from master to main

### PR DESCRIPTION
**Pull request by VasishtaShastry**
Apart from changing branch name, addressed
1. Disparity in usage of cases in True/true, False/false
2. Added short description about the suite.

Signed-off-by: Vasishta <vashastr@redhat.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by ckulal — APPROVED** [review]
lgtm

**Comment by ckulal** [comment]
Can you please attach log here in this PR

**Comment by VasishtaShastry** [comment]
@ckulal currently installation is blocked, will re-run once its solved

**Review by psathyan — APPROVED** [review]

**Comment by VasishtaShastry** [comment]
Log - cephci-jenkins/cephci-run-FPXS6W/6_rbd_krbd_exclusive_0.log

**Pull request merged**
