### PR TITLE
rgw: nfs-ganesha upgrade tests added

### PR DESCRIPTION
**Pull request by gauravsitlani**
Signed-off-by: gauravsitlani <gsitlani@redhat.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs

NFS Ganesha upgrade tests from 4.2 to latest 4.x added. 
[Logs.1](http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-MQXPMV/) 

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test

### CODE REVIEW

**Comment by mkasturi18** [comment]
@gauravsitlani , as discussed could you please integrate one or two NFS test scenarios to any of the existing upgrade suite. This would help in having a consolidated upgrade

**Comment by veera-raghava-reddy** [comment]
@gauravsitlani THis PR is in Open state for a long time. Cna you update ETA to close thi PR?

**Comment by psathyan** [comment]
@gauravsitlani any update on this PR. 

Kindly let me know if you need any clarification on the above review.

**Comment by gauravsitlani** [comment]
@psathyan @veera-raghava-reddy sure, I'm working on it along @vivekanandan-k-rh to achieve closure here by this week.

**Comment by gauravsitlani** [comment]
Thanks @vivekanandan-k-rh

**Comment by gauravsitlani** [comment]
Hi @psathyan made the changes based on feedback provided in : https://github.com/red-hat-storage/cephci/pull/1282#issuecomment-1070533165

**Review by udaysk23 — DISMISSED** [review]
lgtm

**Comment by psathyan** [comment]
I am bit concerned that the overall execution time is more than 3 hours...

**Review by psathyan — APPROVED** [review]

**Pull request merged**
