### PR TITLE
cephadm: Add polarion test IDs

### PR DESCRIPTION
**Pull request by sunilkumarn417**
Signed-off-by: sunilkumarn417 <sunnagar@redhat.com>

- Associate polarion test case IDs with cephadm test suite

### CODE REVIEW

**Comment by rakeshgm** [comment]
have you also linked the scripts in polarion and mark it as automated ?

**Comment by veera-raghava-reddy** [comment]
For some scripts we have two Test IDs. Can those tests be merged?

**Comment by sunilkumarn417** [comment]
> have you also linked the scripts in polarion and mark it as automated ?

Done.

**Comment by sunilkumarn417** [comment]
> For some scripts we have two Test IDs. Can those tests be merged?

https://github.com/red-hat-storage/cephci/blob/01d5e0594e0c69e5edaf6092ac595646101b63e6/utility/polarion.py#L30
This polarion IDS are split here in the above line of code and then considered individually for updation.

**Comment by rakeshgm** [comment]
> For some scripts we have two Test IDs. Can those tests be merged?

We can have comma separated values in the yaml

**Comment by rakeshgm** [comment]
@sunilkumarn417 some of these tests are not approved in polarion. Can you check on them again .

**Comment by veera-raghava-reddy** [comment]
@sunilkumarn417 any update?

**Comment by sunilkumarn417** [comment]
> @sunilkumarn417 any update?

Need approvals from team, will work on it.

**Comment by psathyan** [comment]
> > @sunilkumarn417 any update?
> 
> Need approvals from team, will work on it.

@sunilkumarn417 any progress? If they are not approved, would it make sense to remove the ids and add them once it is approved

**Comment by sunilkumarn417** [comment]
> > > @sunilkumarn417 any update?
> > 
> > 
> > Need approvals from team, will work on it.
> 
> @sunilkumarn417 any progress? If they are not approved, would it make sense to remove the ids and add them once it is approved

@psathyan , Team still working on it.
IMO, closing this PR would be good for now. we can re-open or create new PR when all polarion test ID's are in appropriate state.

**Comment by psathyan** [comment]
@sunilkumarn417 please go ahead and close the PR, let's add an issue in the backlog so that we don't lose track of the changes required

**Comment by sunilkumarn417** [comment]
closing this PR as still few polarion tests are need to be approved.

**Pull request closed without merging**
