### PR TITLE
Adding RADOS features to 5.2 metadata file

### PR DESCRIPTION
**Pull request by tintumathew10**
Signed-off-by: tintumathew10 <tmathew@redhat.com>

Adding RADOS features to 5.2 metadata file.

### CODE REVIEW

**Comment by neha-gangadhar** [comment]
Looks good to me.

**Review by pdhiran — DISMISSED** [review]
Looks good

**Comment by pdhiran** [comment]
1 Question. Are we planning to have one metadata file per RHCS release?

**Review by neha-gangadhar — DISMISSED** [review]

**Comment by tintumathew10** [comment]
yes Pawan, going forward there will be a single metadata file for each release.

**Comment by rahullepakshi** [comment]
@tintumathew10 With Ref- [[Metadata File](https://docs.engineering.redhat.com/display/rhcsqe/Metadata+File)](https://docs.engineering.redhat.com/display/rhcsqe/Metadata+File) All tier-3 and above test suites should be part of system testing and should have the tag system specified under their metadata. All tier-3 will not be run as part of pipeline but will be run as part of system testing. Could you again review RADOS tier-3 tests in this PR? 
FYI - @manasagowri

**Comment by pdhiran** [comment]
Please cleanup The Commit history.

**Comment by tintumathew10** [comment]
Will be creating a clean PR.

**Pull request closed without merging**
