### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mykaul**
# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs

# Checklist:

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test

### CODE REVIEW

**Comment by rakeshgm** [comment]
@mykaul Thanks for the PR. Can you please sign the commit.

**Comment by mykaul** [comment]
> @mykaul Thanks for the PR. Can you please sign the commit.

No idea how - I did the edit directly from Github...

**Comment by sunilkumarn417** [comment]
> > @mykaul Thanks for the PR. Can you please sign the commit.
> 
> No idea how - I did the edit directly from Github...

Hi @mykaul ,

This command will be helpful in adding Signed-off-by line by the committer  `git commit -s` .
```       
-s, --signoff
           Add Signed-off-by line by the committer at the end of the commit log message. The meaning of a signoff depends on the project, but it typically certifies that committer has
           the rights to submit this work under the same license and agrees to a Developer Certificate of Origin (see http://developercertificate.org/ for more information).

```
Thanks

**Comment by mykaul** [comment]
@sunilkumarn417 - as I mentioned above, I've edited the file **directly** in Github...

**Review by rakeshgm — APPROVED** [review]

**Pull request merged**
