### PR TITLE
Squid test suites

### PR DESCRIPTION
**Pull request by sunilkumarn417**
# Description

- NVMe suites for Squid pipeline

### CODE REVIEW

**Review by vamahaja — CHANGES_REQUESTED** [review]
@sunilkumarn417 remove refernces for reef

**Review by sunilangadi2 — CHANGES_REQUESTED** [review]
@sunilkumarn417 you forgot to change comments in cluster configuration file to use for squid test suites.

**Comment by sunilkumarn417** [comment]
> @sunilkumarn417 remove refernces for reef

Updated

**Review by vamahaja — APPROVED** [review]

**Review by sunilangadi2 — APPROVED** [review]
Updated.

**Pull request merged**
