### PR TITLE
Adding CEPHFS test suite for 5.2 and correction in 4.3 yaml file

### PR DESCRIPTION
**Pull request by rkhambad**
Signed-off-by: Rajendra Khambadkar <rkhambad@rkhambad.remote.csb>

### CODE REVIEW

**Review by manasagowri — APPROVED** [review]
LGTM

**Review by hkadam134 — APPROVED** [review]
Looks Good

**Comment by manasagowri** [comment]
@AmarnatReddy @hkadam134 @VasishtaShastry @anrao19  Could any one of you please review this yaml file and let us know if the test suite mapping to the tiers looks good.

As of now we are planning to have only one basic sanity test suite in tier-0, so we have moved your tier-0 to tier-1. Please let us know if that's okay or you want it in any other tier other than tier-0. 
Note : Consider that the tier definitions should conform to the same standards we use for defining tiers in polarion.

**Review by anrao19 — APPROVED** [review]
LGTM

**Review by psathyan — APPROVED** [review]

**Pull request merged**
