### PR TITLE
[TFA][DMFG][Cephadm][OS-Tuning-Profile]Updated mount value

### PR DESCRIPTION
**Pull request by MohitBis**
[TFA][DMFG][Cephadm][OS-Tuning-Profile]Updated mount value

### CODE REVIEW

**Comment by MohitBis** [comment]
Log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-Q1K42J/

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by vinpapnoi — APPROVED** [review]
LGTM

**Review by tintumathew10 — APPROVED** [review]
LGTM

**Pull request merged**
