### PR TITLE
[CephAdm] [Quincy] Adding test suite.

### PR DESCRIPTION
**Pull request by MohitBis**
[CephAdm] [Quincy] Adding test suite for quincy.

New Tiers:
tier-1_test-container-cli-args.yaml
tier-1_skip_dashboard.yaml
tier-1_ssl_dashboard_port.yaml
tier-2_multiple_subnet_openstack_only.yaml

### CODE REVIEW

**Comment by MohitBis** [comment]
Logs:
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-A7HJW8/
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-O51VCK/
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-2SYVKG/
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-WM8OF0/
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-WEIQVQ/

**Review by pranavprakash20 — DISMISSED** [review]
LGTM

**Review by vamahaja — APPROVED** [review]

**Review by vamahaja — APPROVED** [review]

**Comment by vamahaja** [comment]
@manasagowri @tintumathew10 please reivew changes in pipeline

**Review by manasagowri — COMMENTED** [review]
LGTM

**Review by tintumathew10 — COMMENTED** [review]
LGTM.

**Review by manasagowri — APPROVED** [review]
Team review is done. Merging the PR

**Pull request merged**
