### PR TITLE
fix subsystem NQN for 8.0

### PR DESCRIPTION
**Pull request by HaruChebrolu**
# Description

Fix for subsystem NQN creation according to changes mentioned in 
https://ibm-systems-storage.slack.com/archives/C05AM6G7ZF1/p1725459352732749?thread_ts=1725261466.719659&cid=C05AM6G7ZF1

Please find below logs:
gateway_opeartions suite: http://magna002.ceph.redhat.com/cephci-jenkins/harika/cephci-run-BZEND5/
regression suite: http://magna002.ceph.redhat.com/cephci-jenkins/harika/cephci-run-SB4ZOA
sanity: http://magna002.ceph.redhat.com/cephci-jenkins/harika/cephci-run-RTW6LJ

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [x] Review the automation design
- [x] Implement the test script and perform test runs
- [x] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by rahullepakshi** [comment]
@HaruChebrolu Please do not make changes to scale test suites and modules related to scale "tests/nvmeof/test_ceph_nvmeof_gateway_sub_scale.py" I want them with nqn.group at squid.

At squid, please make changes to entire CLI test suite. Make be we can have 2 suites(or merge if its okay), one with "-do-not-append" which may not require much changes other than subsystem add and one with nqn.groupname and this requires lot of changes wherever subsystem is  needed

**Comment by HaruChebrolu** [comment]
> @HaruChebrolu Please do not make changes to scale test suites and modules related to scale "tests/nvmeof/test_ceph_nvmeof_gateway_sub_scale.py" I want them with nqn.group at squid.
> 
> At squid, please make changes to entire CLI test suite. Make be we can have 2 suites(or merge if its okay), one with "-do-not-append" which may not require much changes other than subsystem add and one with nqn.groupname and this requires lot of changes wherever subsystem is needed

We have CLIs testing with nqn.groupname in gateway_operations suite and for testing nqn.group I will have a separate testcase covering this. Lets merge this to not to regression pipelines break.
I will remove changes made in scale tests

**Comment by HaruChebrolu** [comment]
> > @HaruChebrolu Please do not make changes to scale test suites and modules related to scale "tests/nvmeof/test_ceph_nvmeof_gateway_sub_scale.py" I want them with nqn.group at squid.
> > At squid, please make changes to entire CLI test suite. Make be we can have 2 suites(or merge if its okay), one with "-do-not-append" which may not require much changes other than subsystem add and one with nqn.groupname and this requires lot of changes wherever subsystem is needed
> 
> We have CLIs testing with nqn.groupname in gateway_operations suite and for testing nqn.group I will have a separate testcase covering this. Lets merge this to not to regression pipelines break. I will remove changes made in scale tests

@rahullepakshi Removed

**Review by rahullepakshi — APPROVED** [review]

**Review by Manohar-Murthy — APPROVED** [review]
lgtm

**Pull request merged**
