### PR TITLE
[SuiteFix] Fix tier-0-cephadm suite

### PR DESCRIPTION
**Pull request by pranavprakash20**
# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by pranavprakash20** [comment]
Issue: 
The test_validate_safe_stop_hosts fails with error Cannot find host. The issue is the node is been tried to access before adding to the cluster. 

Solution:
Call this test post adding all hosts to the cluster

**Comment by pranavprakash20** [comment]
run log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-WEZIF1/

**Review by MohitBis — APPROVED** [review]
LGTM

**Review by tintumathew10 — APPROVED** [review]
lgtm

**Pull request merged**
