### PR TITLE
[Nfs Ganesha][Test] Add test to verify file lock with root squash

### PR DESCRIPTION
**Pull request by pranavprakash20**
# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by pranavprakash20** [comment]
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-7G7SZ7/

**Comment by pranavprakash20** [comment]
Log : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-BLDT97/
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-D54W34/

**Review by MohitBis — APPROVED** [review]
LGTM

**Review by msainiRedhat — APPROVED** [review]
LGTM

**Review by vdas-redhat — APPROVED** [review]
LGTM

**Pull request merged**
