### PR TITLE
Merging suites with common conf

### PR DESCRIPTION
**Pull request by AmarnatReddy**
# Description
Merging suites with common conf

Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-0RHCHA/

We had 1 failure which was script issue corrected and re-run passed
Re-run Log : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1JFLMF/ 

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by neha-gangadhar** [comment]
@AmarnatReddy As we are merging the tests, please review the polarion "tier" fields and also lets name the suite to capture scenarios covered in the new merged suite.

**Comment by AmarnatReddy** [comment]
> @AmarnatReddy As we are merging the tests, please review the polarion "tier" fields and also lets name the suite to capture scenarios covered in the new merged suite.

Hi Neha,
We have grouped the suites that are part of Regression tier.
I have merged four suites 

1. tier-2_fs.yaml
2. tier-2_cephfs_test-multifs.yaml
3. tier-2_cephfs_test-quota.yaml
4. tier-2_cephfs_test-snapshot-clone.yaml

So I named it as `tier-2_fs_mutlifs_quota_snaphost.yaml`

Regards,
Amarnath

**Comment by neha-gangadhar** [comment]
Is this test being merged in differnet suite? snapshot_nfs_mount? which is currently part of tier-2_cephfs_test-multifs.yaml

**Comment by AmarnatReddy** [comment]
> Is this test being merged in differnet suite? snapshot_nfs_mount? which is currently part of tier-2_cephfs_test-multifs.yaml

Hi Neha,

Thank you for catching that! I’m surprised it was missed, but I’ve now added it.

Regards,
Amarnath

**Review by hkadam134 — APPROVED** [review]
/lgtm

**Review by neha-gangadhar — APPROVED** [review]
Approved

**Pull request merged**
