### PR TITLE
Verify deletion of parent image when clone is flattened when V2clone is enabled

### PR DESCRIPTION
**Pull request by preethisn**
Signed-off-by: Preethi Nataraj <pnataraj@localhost.localdomain>

# Description
Verify deletion of parent image snapshot when clone is flattened when V2clone is enabled

### CODE REVIEW

**Review by Manohar-Murthy — COMMENTED** [review]
Please update the title to reflect the code. Code is deleting image and title says deletion of snapshot.

**Comment by preethisn** [comment]
> 

Updated the title and polarion steps to avoid confusion.

**Comment by preethisn** [comment]
latest log attached - http://magna002.ceph.redhat.com/ceph-qe-logs/Preethi/clones_creation_with_v2clone_format_0.log

**Comment by preethisn** [comment]
code is working as expected- We have found the regression bug with this PR
https://bugzilla.redhat.com/show_bug.cgi?id=2089906

**Review by Manohar-Murthy — APPROVED** [review]
lgtm.

**Pull request merged**
