### PR TITLE
Adding log rotation policy

### PR DESCRIPTION
**Pull request by AmarnatReddy**
# Description
Adding log rotation policy

This update introduces a simple log rotation policy to efficiently manage log files. It addresses the challenge of handling large log files, which can become impractical to access directly in web browsers.

With this enhancement, log files are automatically rotated when they reach a specified size limit, ensuring that only a predetermined number of recent logs are retained. For example, in the provided configuration, the log rotation is set to retain the latest 20 logs with a maximum size of 10 MB each which means we get **200 MB logs for 1 test case**

This streamlined approach optimizes log management, preventing log files from becoming excessively large and facilitating easier access to recent logs through simplified file naming conventions. This helps Baremetal and scale tests which will produce more logs

Used below config for collecting below logs 
```
_handler = logging.handlers.RotatingFileHandler(
            test_logfile,
            maxBytes=1 * 512 * 512,  # Set the maximum log file size to 10 MB
            backupCount=5,  # Keep up to 5 old log files)
        )
```

In the below example, log has been rotated for cluster_deployment where we have cluster_deployment_0.log.3 is the starting log and cluster_deployment_0.log is latest log.
In Index.html it will point to cluster_deployment_0.log
Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-0JNKW5 
```
Logs : 
(venv) amk@magna002:~/log_rot/cephci$ ls -lrt /ceph/cephci-jenkins/cephci-run-0JNKW5
total 1451
-rw-rw-r-- 1 amk amk  14691 Feb 10 23:15 startup.log
-rw-rw-r-- 1 amk amk      0 Feb 10 23:15 setup_install_pre-requisistes_0.err
-rw-rw-r-- 1 amk amk  65799 Feb 10 23:21 setup_install_pre-requisistes_0.log
-rw-rw-r-- 1 amk amk 245660 Feb 10 23:31 cluster_deployment_0.log.3
-rw-rw-r-- 1 amk amk 134286 Feb 10 23:31 cluster_deployment_0.log.2
-rw-rw-r-- 1 amk amk 471955 Feb 10 23:31 cluster_deployment_0.log.1
-rw-rw-r-- 1 amk amk 374601 Feb 10 23:31 cluster_deployment_0.err
-rw-rw-r-- 1 amk amk 108742 Feb 10 23:31 cluster_deployment_0.log
-rw-rw-r-- 1 amk amk      0 Feb 10 23:31 configure_client_0.err
-rw-rw-r-- 1 amk amk   3612 Feb 10 23:32 configure_client_0.log
-rw-rw-r-- 1 amk amk      0 Feb 10 23:32 cephfs_default_values_for_mds_0.err
-rw-rw-r-- 1 amk amk   4940 Feb 10 23:33 cephfs_default_values_for_mds_0.log
-rw-rw-r-- 1 amk amk      0 Feb 10 23:33 cephfs-basics_0.err
-rw-rw-r-- 1 amk amk      0 Feb 10 23:35 nfs-ganesha_with_cephfs_0.err
-rw-rw-r-- 1 amk amk  20915 Feb 10 23:35 cephfs-basics_0.log
-rw-rw-r-- 1 amk amk  11486 Feb 10 23:37 nfs-ganesha_with_cephfs_0.log
-rw-rw-r-- 1 amk amk      0 Feb 10 23:37 Increase_and_Decrease_of_MDS_0.err
-rw-rw-r-- 1 amk amk   9707 Feb 10 23:37 Increase_and_Decrease_of_MDS_0.log
-rw-rw-r-- 1 amk amk      0 Feb 10 23:37 generate_sosreport_0.err
-rw-rw-r-- 1 amk amk      2 Feb 10 23:40 run_summary.json
-rw-rw-r-- 1 amk amk   7421 Feb 10 23:40 generate_sosreport_0.log
-rw-rw-r-- 1 amk amk   7916 Feb 10 23:40 index.html

```

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by neha-gangadhar** [comment]
Thank you for adding log rotation. @sunilkumarn417 @tintumathew10 @vamahaja Any thoughts? Please review.

**Comment by vamahaja** [comment]
@neha-gangadhar @AmarnatReddy thanks for PR. We will update CI to handle these log tatation accordinlgy.

**Review by vamahaja — COMMENTED** [review]
LGTM

**Review by tintumathew10 — COMMENTED** [review]
LGTM

**Review by neha-gangadhar — APPROVED** [review]
Approved

**Review by neha-gangadhar — APPROVED** [review]
lgtm

**Review by vamahaja — APPROVED** [review]

**Review by tintumathew10 — DISMISSED** [review]

**Review by tintumathew10 — APPROVED** [review]

**Pull request merged**
