### PR TITLE
[NFS-Ganesha][Deplloyment]Add automation support for deployment using…

### PR DESCRIPTION
**Pull request by MohitBis**
[NFS-Ganesha][Deplloyment]Add automation support for deployment using…

Scenario Covered:
Deploy NFS-Ganesha cluster with spec file 4 Nodes
Deploy NFS-Ganesha cluster with spec file 8 Nodes

### CODE REVIEW

**Comment by MohitBis** [comment]
Log : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-U4OT2C/

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by msainiRedhat — APPROVED** [review]
LGTM

**Review by vdas-redhat — APPROVED** [review]
LGTM

**Pull request merged**
