### PR TITLE
docker to podman migration with ansible

### PR DESCRIPTION
**Pull request by Ameenasuhani**
# Description
Docker to podman migration with ansible

# Checklist:

- [x] Create a test case in Polarion reviewed and approved.
- [x] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [x] Review the automation design
- [x] Implement the test script and perform test runs
- [x] Submit PR for code review and approve
- [x] Update Polarin Test with Automation script details and update automation fields
- [x] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test

Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1597252543435/
lvm: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1597306164331/

### CODE REVIEW

**Comment by rakeshgm** [comment]
@Ameenasuhani this looks like a new TC . Can you follow and update the checklist in the PR.

**Comment by Ameenasuhani** [comment]
@rakeshgm yes, I'm creating a test case in polarion now. Once I attach everything  I will request a review

**Comment by rakeshgm** [comment]
the changes look god to me, but we should not forget to run these tests for all the releases. unless we add it to an existing yaml
@XDsubhash what do you think. this holds true for other tests too.

**Review by rakeshgm — APPROVED** [review]

**Comment by XDsubhash** [comment]
@rakeshgm agree..either manually run or the cli needs to be added jenkins p1 jobs

**Pull request merged**
