### PR TITLE
Handle NFS failures due to BZ2228066

### PR DESCRIPTION
**Pull request by sumabai**
# Description
BZ 2228066 design changes caused more nfs failures in test environment due to laggy OSDs.
Added test flag "defer_client_eviction_on_laggy_osds set to false" to overcome failures.

Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-MZMYYB/. This had 4 failures, less compared to 16 without test flag.
Rerun Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-UGFNGP/, no failures when rerun on same setup. 2 known BZs exists in this log.

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by hkadam134 — COMMENTED** [review]
Can we add this conf to test-clients.yaml also ?

We tend to hit the issue in the client eviction test case.

**Comment by sumabai** [comment]
> Can we add this conf to test-clients.yaml also ?
> 
> We tend to hit the issue in the client eviction test case.

Added

**Comment by hkadam134** [comment]
LGTM

Can we wait until the next Weekly Runs are executed and add these changes wherever the issues are seen?

**Comment by neha-gangadhar** [comment]
Next weekly runs is after a week. We do not have to keep a PR open for a week to check other suite failures. If we see other suite failures due to same issue, new PR can fix them.

**Review by neha-gangadhar — APPROVED** [review]

**Pull request merged**
