### PR TITLE
added rgw tests before and after upgrade

### PR DESCRIPTION
**Pull request by Ameenasuhani**
Description: Added rgw tests before and after upgrade
Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1596623535529/

### CODE REVIEW

**Comment by rakeshgm** [comment]
@Ameenasuhani add more bucket operation tests, versioning tests and lifecycle tests. looks for the tests here 
from here. https://github.com/red-hat-storage/cephci/blob/master/suites/nautilus/rgw/sanity_rgw.yaml#L44

**Comment by Ameenasuhani** [comment]
@rakeshgm okay. I will go ahead and add them

**Comment by Ameenasuhani** [comment]
logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1599487152464/result.html

**Review by rakeshgm — COMMENTED** [review]
looks good

**Comment by rakeshgm** [comment]
@TejasC88, what do you think.

**Review by TejasC88 — APPROVED** [review]

**Comment by TejasC88** [comment]
I agree , looks good

**Pull request merged**
