### PR TITLE
[NFS-Ganesha][Automation]Add config edit scenarios

### PR DESCRIPTION
**Pull request by MohitBis**
[NFS-Ganesha][Automation]Add config edit scenarios
Scenario:
1. Edit the export config to mount with RO
2. Edit the export config to mount to allow access to only 1 client

### CODE REVIEW

**Comment by MohitBis** [comment]
Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-SPAITU/

**Review by pranavprakash20 — DISMISSED** [review]
LGTM

**Review by msainiRedhat — DISMISSED** [review]
LGTM

**Review by vdas-redhat — DISMISSED** [review]
LGTM

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by msainiRedhat — APPROVED** [review]

**Review by vdas-redhat — APPROVED** [review]
Ok now

**Pull request merged**
