### PR TITLE
fix rename vol_mgmt file and test name

### PR DESCRIPTION
**Pull request by julpark-rh**
Fixing dir name for the suite and file name

Signed-off-by: julpark-rh <yonhyun@gmail.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by AmarnatReddy — DISMISSED** [review]
Can change for **cephfs_vol_mgmt_subvolgroup_gid_uid.py** also.
This is also pointing to wrong folder

**Review by AmarnatReddy — COMMENTED** [review]
Can change for cephfs_vol_mgmt_subvolgroup_gid_uid.py also.
This is also pointing to wrong folder

**Comment by yogesh-mane** [comment]
Hi @julpark-rh , can you share run logs?

**Review by hkadam134 — APPROVED** [review]
LGTM

**Comment by julpark-rh** [comment]
Re-submit  PR

**Pull request closed without merging**
