### PR TITLE
Set mon_allow_pool_delete for ceph version >5

### PR DESCRIPTION
**Pull request by VasishtaShastry**
Along with mon_allow_pool_delete, removed ceph mon restart
as it should not be required.

Fixes: #1293

Signed-off-by: Vasishta <vashastr@redhat.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by VasishtaShastry** [comment]
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-ZIRRTQ

I could not try with rhbuild 6.0 but I think this should work with 6.0 as 
We are fetching ceph_version from rhbuild[0] and converting it into `int`
https://github.com/red-hat-storage/cephci/blob/master/tests/rbd/rbd_utils.py#L25

removing mon restart is also working fine http://pastebin.test.redhat.com/1049933

setting mon_allow_pool_delete to tru is being handled using ceph-ansible config overrides in <5

**Review by psathyan — COMMENTED** [review]
Looks good... 

Could we have one run which covers the pool delete?

**Comment by VasishtaShastry** [comment]
@psathyan Above run involves pool deletion 
http://pastebin.test.redhat.com/1050284

**Review by pdhiran — APPROVED** [review]
Looks good

**Review by psathyan — APPROVED** [review]

**Pull request merged**
