### PR TITLE
[NFS-Ganesha][Phase 2]Add test case automation

### PR DESCRIPTION
**Pull request by MohitBis**
Scenario: Modifying file attributes such as size, modification time, and access time.

### CODE REVIEW

**Comment by MohitBis** [comment]
Log : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-OXVYIM

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by msainiRedhat — APPROVED** [review]
LGTM

**Review by vdas-redhat — APPROVED** [review]
LGTM

**Pull request merged**
