### PR TITLE
[Test] Add test to add host to cluster using `ceph_orch_host module`

### PR DESCRIPTION
**Pull request by vamahaja**
Signed-off-by: Vaibhav Mahajan <vamahaja@redhat.com>

### CODE REVIEW

**Comment by sayaleeraut** [comment]
LGTM

**Comment by msainiRedhat** [comment]
LGTM

**Comment by vamahaja** [comment]
Quincy Test Run - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-mnkh2/

**Review by MohitBis — APPROVED** [review]
LGTM

**Review by MohitBis — DISMISSED** [review]
LGTM

**Comment by vamahaja** [comment]
Pacific Test Run - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-l86lk/

**Review by pranavprakash20 — APPROVED** [review]
LGMT

**Review by MohitBis — APPROVED** [review]
LGTM

**Pull request merged**
