### PR TITLE
Updated dashboard images

### PR DESCRIPTION
**Pull request by sunilangadi2**
# Description
It's just minor update From 4.2z1 onwards dashboard images got updated as per here https://bugzilla.redhat.com/show_bug.cgi?id=1925350
hence updated all the dashboard images in the suite

Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1614142875407/

# Checklist:

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test

### CODE REVIEW

**Comment by sunilangadi2** [comment]
@sunilkumarn417 Please review and merge bcz we can use these updated images in upcoming releases

**Comment by sunilkumarn417** [comment]
> @sunilkumarn417 Please review and merge bcz we can use these updated images in upcoming releases

@sunilangadi2 can you please provide more information.

**Comment by sunilangadi2** [comment]
@sunilkumarn417 In 4.2 z1 onwards dashboard images got updated hence updated all dashboard images
Refer : https://bugzilla.redhat.com/show_bug.cgi?id=1925350

**Comment by sunilkumarn417** [comment]
> @sunilkumarn417 In 4.2 z1 onwards dashboard images got updated hence updated all dashboard images
> Refer : https://bugzilla.redhat.com/show_bug.cgi?id=1925350

will it be okay if there be any build in 4.1 z-streams?

**Comment by sunilangadi2** [comment]
> > @sunilkumarn417 In 4.2 z1 onwards dashboard images got updated hence updated all dashboard images
> > Refer : https://bugzilla.redhat.com/show_bug.cgi?id=1925350
> 
> will it be okay if there be any build in 4.1 z-streams?

Yes, It's fine.

**Review by VasishtaShastry — APPROVED** [review]
Looks good to me
One file was missed, I've sent a fix for the same

**Review by psathyan — APPROVED** [review]

**Pull request merged**
