### PR TITLE
Tuning quincy rbd suite and adding stderr to log error

### PR DESCRIPTION
**Pull request by VasishtaShastry**
1) Tuning Quincy suite to branch name changes in upstream.
2) Adding stderr to log.error to help users to identify issue in reportportal itself.
3) Adding workaround info to logs to avoid users looking at the logs getting confused

Signed-off-by: Vasishta <vashastr@redhat.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by VasishtaShastry** [comment]
Logs - cephci-jenkins/cephci-run-0ATVUT/configure_client_0.log

**Comment by VasishtaShastry** [comment]
@AmarnatReddy Can you please review changes to ceph.py ?
@red-hat-storage/ceph-qe-block Can you please review changes to rbd suite ?

**Comment by VasishtaShastry** [comment]
@TejasC88 Fixed suite being used for upstream

**Review by Manohar-Murthy — APPROVED** [review]
Approving based on Block group review.

**Pull request merged**
