### PR TITLE
client metrics negative case

### PR DESCRIPTION
**Pull request by julpark-rh**
# Description
Client metrics negative test case
1. Run IOs on the mounted directory
2. Do other operations like increasing dentry, inode, opened_files, etc
3. Reboot the MDS node
4. Check if the metrics are changed as expected

https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83588357

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-ESBTE4/

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by hkadam134** [comment]
/2024-06-10 14:00:55,885 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - cap_hits: 350697 cap_hits: 352338
2024-06-10 14:00:55,888 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:136 - Skipping cap_hits as it is not stable
2024-06-10 14:00:55,891 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - cap_miss: 524 cap_miss: 525
2024-06-10 14:00:55,893 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:136 - Skipping cap_miss as it is not stable
2024-06-10 14:00:55,896 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - avg_read_latency: 0.0 avg_read_latency: 0.0
2024-06-10 14:00:55,898 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - avg_write_latency: 0.0 avg_write_latency: 0.0
2024-06-10 14:00:55,901 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - avg_metadata_latency: 0.0 avg_metadata_latency: 0.0
2024-06-10 14:00:55,903 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - dentry_lease_hits: 212 dentry_lease_hits: 212
2024-06-10 14:00:55,905 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - dentry_lease_miss: 100 dentry_lease_miss: 100
2024-06-10 14:00:55,907 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - opened_files: 10 opened_files: 10
2024-06-10 14:00:55,909 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - opened_inodes: 213 opened_inodes: 111
2024-06-10 14:00:55,910 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - pinned_icaps: 214 pinned_icaps: 112
2024-06-10 14:00:55,912 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_inodes: 213 total_inodes: 111
2024-06-10 14:00:55,913 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_read_ops: 65784 total_read_ops: 65784
2024-06-10 14:00:55,915 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_read_size: 11687986782 total_read_size: 11687986782
2024-06-10 14:00:55,917 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_write_ops: 122991 total_write_ops: 122991
2024-06-10 14:00:55,918 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_write_size: 10737419870 total_write_size: 10737419870

**Comment by julpark-rh** [comment]
> `2024-06-10 14:00:55,885 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - cap_hits: 350697 cap_hits: 352338 2024-06-10 14:00:55,888 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:136 - Skipping cap_hits as it is not stable 2024-06-10 14:00:55,891 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - cap_miss: 524 cap_miss: 525 2024-06-10 14:00:55,893 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:136 - Skipping cap_miss as it is not stable 2024-06-10 14:00:55,896 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - avg_read_latency: 0.0 avg_read_latency: 0.0 2024-06-10 14:00:55,898 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - avg_write_latency: 0.0 avg_write_latency: 0.0 2024-06-10 14:00:55,901 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - avg_metadata_latency: 0.0 avg_metadata_latency: 0.0 2024-06-10 14:00:55,903 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - dentry_lease_hits: 212 dentry_lease_hits: 212 2024-06-10 14:00:55,905 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - dentry_lease_miss: 100 dentry_lease_miss: 100 2024-06-10 14:00:55,907 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - opened_files: 10 opened_files: 10 2024-06-10 14:00:55,909 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - opened_inodes: 213 opened_inodes: 111 2024-06-10 14:00:55,910 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - pinned_icaps: 214 pinned_icaps: 112 2024-06-10 14:00:55,912 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_inodes: 213 total_inodes: 111 2024-06-10 14:00:55,913 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_read_ops: 65784 total_read_ops: 65784 2024-06-10 14:00:55,915 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_read_size: 11687986782 total_read_size: 11687986782 2024-06-10 14:00:55,917 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_write_ops: 122991 total_write_ops: 122991 2024-06-10 14:00:55,918 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_write_size: 10737419870 total_write_size: 10737419870`
> 
> I see differences in metrics before and after reboot, few are marked as not stable, and few are without any validation. What is expected here?

Yes.

opened_inodes: 213 opened_inodes: 111
pinned_icaps: 214 pinned_icaps: 112
total_inodes: 213 total_inodes: 111

these three metrics should be decreased because from disconnection of MDS clears all the metadata cache and it went back to the initial state. I confirmed with Jos regarding to this.

Not only that "cap_hits" and "cap_miss" increases slightly. This is expected as well. -> I also confirmed with Jos as well.

**Comment by hkadam134** [comment]
> > `2024-06-10 14:00:55,885 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - cap_hits: 350697 cap_hits: 352338 2024-06-10 14:00:55,888 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:136 - Skipping cap_hits as it is not stable 2024-06-10 14:00:55,891 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - cap_miss: 524 cap_miss: 525 2024-06-10 14:00:55,893 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:136 - Skipping cap_miss as it is not stable 2024-06-10 14:00:55,896 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - avg_read_latency: 0.0 avg_read_latency: 0.0 2024-06-10 14:00:55,898 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - avg_write_latency: 0.0 avg_write_latency: 0.0 2024-06-10 14:00:55,901 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - avg_metadata_latency: 0.0 avg_metadata_latency: 0.0 2024-06-10 14:00:55,903 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - dentry_lease_hits: 212 dentry_lease_hits: 212 2024-06-10 14:00:55,905 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - dentry_lease_miss: 100 dentry_lease_miss: 100 2024-06-10 14:00:55,907 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - opened_files: 10 opened_files: 10 2024-06-10 14:00:55,909 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - opened_inodes: 213 opened_inodes: 111 2024-06-10 14:00:55,910 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - pinned_icaps: 214 pinned_icaps: 112 2024-06-10 14:00:55,912 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_inodes: 213 total_inodes: 111 2024-06-10 14:00:55,913 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_read_ops: 65784 total_read_ops: 65784 2024-06-10 14:00:55,915 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_read_size: 11687986782 total_read_size: 11687986782 2024-06-10 14:00:55,917 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_write_ops: 122991 total_write_ops: 122991 2024-06-10 14:00:55,918 (cephci.cephfs_top.metric_nega) [INFO] - cephci.cephci.tests.cephfs.cephfs_top.metric_nega.py:134 - total_write_size: 10737419870 total_write_size: 10737419870`
> > I see differences in metrics before and after reboot, few are marked as not stable, and few are without any validation. What is expected here?
> 
> Yes.
> 
> opened_inodes: 213 opened_inodes: 111 pinned_icaps: 214 pinned_icaps: 112 total_inodes: 213 total_inodes: 111
> 
> these three metrics should be decreased because from disconnection of MDS clears all the metadata cache and it went back to the initial state. I confirmed with Jos regarding to this.
> 
> Not only that "cap_hits" and "cap_miss" increases slightly. This is expected as well. -> I also confirmed with Jos as well.

OK. Thanks for the update.

**Review by hkadam134 — DISMISSED** [review]
lgtm

**Review by neha-gangadhar — APPROVED** [review]
Approved

**Pull request merged**
