### PR TITLE
fix for subvolumegroup force

### PR DESCRIPTION
**Pull request by julpark-rh**
Fix for subvolumegroup delete fix
--force option should make the command succeed
Also added "log.error()" as well.

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-YC2LH5/

Signed-off-by: julpark-rh <yonhyun@gmail.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs

<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by hkadam134** [comment]
@julpark-rh - Can you paste the logs of this run ??

**Comment by julpark-rh** [comment]
> @julpark-rh - Can you paste the logs of this run ??

I have attached the pass log

**Review by hkadam134 — APPROVED** [review]
Looks Good

**Review by AmarnatReddy — APPROVED** [review]
LGTM

**Pull request merged**
