### PR TITLE
CLI changes to QOS suite for new HA build

### PR DESCRIPTION
**Pull request by manasagowri**
Success Logs - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-2ACR8O/

### CODE REVIEW

**Comment by HaruChebrolu** [comment]
LGTM. A very minor comment though this was initially created by me.
Now I feel, we can include qos CLI within gateway_operations suite itself. What do you think?

**Comment by manasagowri** [comment]
> LGTM. A very minor comment though this was initially created by me. Now I feel, we can include qos CLI within gateway_operations suite itself. What do you think?

This might require some extra testing right. I am not sure now is the right time to spend on it, since I have HA testing as well on priority. We could pick this up post 7.1 release.

What do you think?

**Review by rahullepakshi — APPROVED** [review]

**Review by sunilkumarn417 — COMMENTED** [review]
Hi @manasagowri ,

I think all the commands should be in Gateway operations suite, Lets not have nvmeof_qos suite file at all. Since it just execution of CLIs.

And GW operations suite is the place where run all CLIs.

@HaruChebrolu , Do we have any reason to keep separate file for QOS CLIs execution?

**Comment by HaruChebrolu** [comment]
> Hi @manasagowri ,
> 
> I think all the commands should be in Gateway operations suite, Lets not have nvmeof_qos suite file at all. Since it just execution of CLIs.
> 
> And GW operations suite is the place where run all CLIs.
> 
> @HaruChebrolu , Do we have any reason to keep separate file for QOS CLIs execution?

At initial phase, to keep it isolate, created a new suite for QoS while we are working on building NVMe framework. Now, its good to merge QoS into gateway_operations by removing qos suite.

**Comment by HaruChebrolu** [comment]
> @HaruChebrolu @sunilkumarn417 I have merged the QOS tests into gateway operations test suite itself. I am unable to copy the success logs to magna because of some issues with magna today. Will do it once the issue is resolved.
> 
> In the meantime could you please review this and let me know if this is okay? Also shall I remove the QOS test suite from the repo?

yes @manasagowri , please remove it

**Review by HaruChebrolu — APPROVED** [review]
LGTM

**Pull request merged**
