### PR TITLE
Adding EC support for System suite

### PR DESCRIPTION
**Pull request by AmarnatReddy**
# Description
Adding EC support for the System suite
With EC : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-9C2HD0/
without EC : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-J3QWVZ/ 

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by hkadam134 — APPROVED** [review]
/lgtm

**Comment by sumabai** [comment]
@AmarnatReddy There are 3 failed logs in run with EC support, of the one analyzed, i see there are few more places in script where fs_name variable needs to be used, without which the script has failed. Like when applying standby-replay, creating subvolgroup and subvolumes...

**Comment by AmarnatReddy** [comment]
> @AmarnatReddy There are 3 failed logs in run with EC support, of the one analyzed, i see there are few more places in script where fs_name variable needs to be used, without which the script has failed. Like when applying standby-replay, creating subvolgroup and subvolumes...

Hi Suma,
I have made the changes and EC Filesystem is getting created and tests are running on it.
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-S9O87Q/ . 
Still it is failing as cluster is going to health_warn state. 
Can you review the log

**Review by neha-gangadhar — APPROVED** [review]
Approved

**Pull request merged**
