### PR TITLE
Inventory files for rhel 8.7 and 9.1

### PR DESCRIPTION
**Pull request by sunilkumarn417**
Signed-off-by: Sunil Kumar Nagaraju <sunnagar@redhat.com>

- Inventory files for RHEL 8.7 and 9.1
- solve root login in rhel 9.1 on IBM env.

Had node deployment sanity test with new fix in `ceph.py` for RHEL-8.7 and RHEL9.1, 9.0  versions on Both IBM environment.

However, still cloud-config not seems to be on PSI and IBM environment for the RHEL version. need to debug more, for now this unblock us in CI pipeline.
```
IBM
=====

RHEL-9.0
-----------
[root@ceph-sunil-3m7rz0-node1-installer ~]# rpm -qa | grep "cloud-init"
cloud-init-21.1-19.el9.noarch
[root@ceph-sunil-3m7rz0-node1-installer ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.0 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.0 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.0"


RHEL-9.1
--------
[root@ceph-sunil-91-iaf6xk-node1-installer ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.1 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.1 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
[root@ceph-sunil-91-iaf6xk-node1-installer ~]# rpm -qa | grep cloud-init
cloud-init-22.1-5.el9.noarch


RHEL-8.7
--------
[root@ceph-sunil-87-18zc1v-node1-installer ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
[root@ceph-sunil-87-18zc1v-node1-installer ~]# rpm -qa | grep cloud-init
cloud-init-22.1-5.el8.noarch


PSI
====


RHEL-9.1
---------
[root@ceph-sunil-91-szgf08-node1-installer ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.1 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.1 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
[root@ceph-sunil-91-szgf08-node1-installer ~]# rpm -qa | grep cloud-init
cloud-init-22.1-5.el9.noarch


RHEL-9.0
---------
[root@ceph-sunil-90-219nrf-node1-installer ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.0 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.0 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.0"
[root@ceph-sunil-90-219nrf-node1-installer ~]# rpm -qa | grep cloud-init
cloud-init-21.1-19.el9_0.4.noarch


RHEL-8.7
--------
[root@ceph-sunil-87-ziyb2t-node1-installer ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
[root@ceph-sunil-87-ziyb2t-node1-installer ~]# rpm -qa | grep cloud-init
cloud-init-22.1-5.el8.noarch

```

**Results: old**
```
PSI
---
**RHCS-6.0 RHEL-9.1 RGW test suite** - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-ZH0FAH/
**RHCS-5.3 RHEL-8.7 Rados test suite** - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-9RRJN9/

IBM:
--------
.venv/bin/python run.py --osp-cred /home/cephuser/osp-cred-ci-2.yaml --instances-name sunil --log-level DEBUG --cloud ibmc --log-dir logs-rgw --suite suites/pacific/rgw/tier-2_rgw_test-using-s3cmd.yaml --global-conf conf/pacific/rgw/tier-0_rgw.yaml --platform rhel-8 --rhbuild 5.3 --inventory conf/inventory/ibm-vpc-rhel-8-latest.yaml --build latest

All test logs located here: /data/jenkins/workspace/Sunil/cephci-1/cephci/logs-rgw

TEST NAME                        TEST DESCRIPTION                                               DURATION                         STATUS                    COMMENTS
setup pre-requisites             Install software pre-requisites for cluster deployment.        0:08:03.464080                   Pass                             
deploy cluster                   RHCS cluster deployment using cephadm.                         0:12:10.505497                   Pass                             
Monitoring Services deployment   Add monitoring services using spec file.                       0:11:35.198699                   Pass                             
S3CMD basic  operations          S3CMD basic  operations                                        0:01:15.691074                   Pass                             
S3CMD large object download wi   S3CMD large object download with GC                            0:02:41.341374                   Pass                             
S3CMD bucket stats consistency   S3CMD bucket stats consistency                                 0:03:46.775332                   Pass                             
S3CMD object header size check   S3CMD object header size check                                 0:00:29.348744                   Pass                             
S3CMD tests                      S3CMD tests, Testing rgw opslog                                0:00:26.051327                   Pass                             
Test single delete marker for    Test single delete marker for versioned object using s3cmd     0:00:28.319424                   Pass                             
2022-11-27 17:13:08,354 - INFO - cephci.run.py:1069 - final rc of test run 0

```

### CODE REVIEW

**Review by Manohar-Murthy — APPROVED** [review]

**Comment by sunilkumarn417** [comment]
Hey Everyone, 

I still issue with root login from RHEL 8.7, where `chpasswd` cloud configuration is not being honored.
However RGW team has already moved their `ceph-qe-scripts` tests to execute `non-root` user and it's already merged. and as per the results updated here, did not notciced any issues so far.

**Comment by mkasturi18** [comment]
Changes lgtm.

**Review by mkasturi18 — APPROVED** [review]

**Review by tintumathew10 — COMMENTED** [review]
@sunilkumarn417 , If at all we want to run the suites against an old version of rhel, do we need to make any chages in cephci?

**Comment by sunilkumarn417** [comment]
> @sunilkumarn417 , If at all we want to run the suites against an old version of rhel, do we need to make any chages in cephci?


@tintumathew10 can you please provide some more context, whether it is for newer builds of RHCS releases or for recreating older environment for hotfix/reproduction?

**Review by tintumathew10 — COMMENTED** [review]
@sunilkumarn417 , I was talking about the recreation of older environment for hotfix/bug reproduction.

**Comment by sunilkumarn417** [comment]
> @sunilkumarn417 , I was talking about the recreation of older environment for hotfix/bug reproduction.

@tintumathew10 , Need more context, we can discuss more about this. However,
- To reproduce the issue, probably may need one inventory file, that is already available.
- To execute hotfix build on all test suites, it could be done at jenkins CI.
- To get any RHCS standalone on particluar rhel version, it is doable as the first one.

**Review by tintumathew10 — COMMENTED** [review]
Thanks for the clarification. Looks good to me.

**Review by manasagowri — COMMENTED** [review]
LGTM

**Comment by AmarnatReddy** [comment]
Hi Sunil,
Do we still need to have the restriction of setting distro **subscription-manager release --set**  in install_prereq.py

**Comment by sunilkumarn417** [comment]
> Hi Sunil, Do we still need to have the restriction of setting distro **subscription-manager release --set** in install_prereq.py

No, Amar. we wanted to test suite on particular RHEL version ?right. so we can still have that changes.

However the changes for root login still cannot unblock the issue, since issue occurs after upgrade to 8.7 or 9.1.

Once we have information in PSI, we could look for final solution.

**Comment by AmarnatReddy** [comment]
LGTM

**Review by AmarnatReddy — APPROVED** [review]
LGTM

**Pull request merged**
