### PR TITLE
Added swift bulk delete testcase

### PR DESCRIPTION
**Pull request by vivekanandan-k-rh**
Added swift bulk delete testcase

Polarion id: CEPH-9753

Passed log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1620045554306/Swift_based_tests_0.log

### CODE REVIEW

**Comment by sunilkumarn417** [comment]
@vivekanandan-k-rh please sign your commit.

**Comment by vivekanandan-k-rh** [comment]
Done @sunilkumarn417

**Comment by rakeshgm** [comment]
@vivekanandan-k-rh  the TC is not marked as automated in polarion and also please add the test script link in automation section.

**Comment by vivekanandan-k-rh** [comment]
@rakeshgm , I have updated the details in polarion. Please review the same

**Review by rakeshgm — APPROVED** [review]

**Pull request merged**
