### PR TITLE
pool_tests.py: Adding PG count and min_size tests

### PR DESCRIPTION
**Pull request by pdhiran**
Adding tests for:
1. PG autoscaler behaviour with mode set to warn
2. Pool behaviour when size == min_size

### CODE REVIEW

**Comment by pdhiran** [comment]
Pass logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-N43QTB

**Review by neha-gangadhar — APPROVED** [review]
Looks good to me.

**Comment by sunilkumarn417** [comment]
> Adding tests for:
> 
> 1. PG autoscaler behaviour with mode set to warn
> 2. Pool behaviour when size == min_size

Hi @pdhiran,

Please update the polarion test case with steps followed and also please update the other fields mainly `description`, `release`, `tags`, `setup`, `steps`.

**Review by tintumathew10 — APPROVED** [review]
LGTM

**Pull request merged**
