### PR TITLE
Correcting the Values for K , M for the EC pool tests in RADOS

### PR DESCRIPTION
**Pull request by pdhiran**
Coreected the values in the suites to configure EC pools with one of the 3 supported configurations
Supported :
k=8 m=3
k=8 m=4
k=4 m=2
Doc : https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/5/html/storage_strategies_guide/erasure_code_pools#erasure_code_profiles

Signed-off-by: Pawan Dhiran <pdhiran@redhat.com>

### CODE REVIEW

**Comment by pdhiran** [comment]
> Looks good to me... do we a need a run with the new changes?

These changes are not completely new, i.e we have had EC pools with k,m values that were modified, That run as expected. This is just a change for those pools which had config other than the recommended one. 

When the tests run properly with non-recommended values, I do not see any reason for them to fail now with the Recommended ones.

I do not feel we need to have runs for merging this change. Let me know your thoughts. If needed, Can be run.

**Comment by pdhiran** [comment]
Pass log : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-WB8RHT/

There is one test failure, but that is due to a SSH connection issue. The actual test case has passed.
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-WB8RHT/EC_Pool_Recovery_Improvement_0.log

2022-08-06 07:42:21,357 - INFO - cephci.pool_tests:110 - Performing restart on osd-18 on host ceph-pdhiran-cidr-wb8rht-node5. Command systemctl restart ceph-567eaf4e-1556-11ed-a17b-fa163e6f0209@osd.18.service
2022-08-06 07:42:21,357 - INFO - cephci.pool_tests:110 - Running command systemctl restart ceph-567eaf4e-1556-11ed-a17b-fa163e6f0209@osd.18.service on 10.0.209.247 timeout 600
2022-08-06 07:52:21,448 - ERROR - cephci.pool_tests:110 - SSHException during cmd: Timeout opening channel.
2022-08-06 07:52:21,449 - ERROR - cephci.pool_tests:110 - Error None during cmd, timeout 600
ceph.ceph.CommandFailed: systemctl restart ceph-567eaf4e-1556-11ed-a17b-fa163e6f0209@osd.18.service Error:   10.0.209.247

**Comment by pdhiran** [comment]
> > I do not feel we need to have runs for merging this change. Let me know your thoughts. If needed, Can be run.
> 
> Let's have a run. As I believe we would need to change the cluster layout to support 8 + 4

Even though we have increased the k,m values to 8 + 4, i.e 12 OSDs in acting set, since our failure domain is OSD, we would not need to change the cluster layout. We have enough OSDs deployed on cluster for both 7 node & 11 node Configs to be able to support these EC pools.

**Comment by pdhiran** [comment]
All Passed logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-2V50KH

**Review by psathyan — APPROVED** [review]

**Pull request merged**
