### PR TITLE
kernel verification enchancement

### PR DESCRIPTION
**Pull request by julpark-rh**
# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by hkadam134 — APPROVED** [review]
/lgtm

**Comment by hkadam134** [comment]
Hi, @julpark-rh - why is the new suite added for kernel verification?

We already have 2 suites for kernel verifications. If those are not needed, can you delete them?

**Comment by julpark-rh** [comment]
> Hi, @julpark-rh - why is the new suite added for kernel verification?
> 
> We already have 2 suites for kernel verifications. If those are not needed, can you delete them?

this is because there are multiple cases such as have to add the repo manually. I thought it could be easier running as it is.

**Review by neha-gangadhar — APPROVED** [review]
Approved

**Pull request merged**
