### PR TITLE
Adding skip_tc for skipping the TC

### PR DESCRIPTION
**Pull request by AmarnatReddy**
# Description
Adding skip_tc for skipping the TC

Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-CP9MDV/ 

Skipped Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-BRICUM/
First run logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-N1R5IK

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by vamahaja** [comment]
IMO this is not correct way to skip the tests. Test cases should be skipped based on the check in test suites or test case.

**Comment by neha-gangadhar** [comment]
@sunilkumarn417 @manasagowri @tintumathew10 @vamahaja Are there any specific improvements suggested ? Can we review the PR and get ACK from all? We would like to start executions for 7.0

**Comment by vamahaja** [comment]
@neha-gangadhar IMO, we should explore other options as well. This will unnecessarily add complexity in the code.

**Comment by AmarnatReddy** [comment]
Hi Vaibhav,
As discussed, can you review this again.
Proposed Doc : https://docs.google.com/document/d/1nC-Ei12ZWcnQx_xlxUO0ZVJoGJ7MOWaIRO2OoAguf2E/edit

**Comment by vamahaja** [comment]
@AmarnatReddy changes looks good. We can go ahead with these changes for now.

**Review by vamahaja — COMMENTED** [review]
LGTM

**Comment by neha-gangadhar** [comment]
@vamahaja @AmarnatReddy Anything pending on the PR to merge? I think only approval was missed with comment and hence in Open state? Please review and approve for auto merge. Thanks

**Comment by vamahaja** [comment]
@AmarnatReddy @neha-gangadhar if all tests with these changes are passed then we can merge this PR.

**Review by vamahaja — APPROVED** [review]

**Pull request merged**
