### PR TITLE
 adding timeout to long running commands

### PR DESCRIPTION
**Pull request by yogesh-mane**
Added 300 seconds timeout for crefi & dd IOs
Added 600 seconds timeout for smafile IOs
Added 3600 seconds timeout for deletion of files commands as it might take a while if debug levels are high & number of files & file size are large.

### CODE REVIEW

**Comment by XDsubhash** [comment]
i wont close the issue yet ,as you dont know why its happening and no proper workaround exists.( no rca)

@yogesh-mane i'll remove the blocker label in the issue,hoping that this patch should unblock this weekend pipeline jobs which should start in couple hrs. i'll merge it for now, will check the p1 pipeline logs on monday and see if any cephfs suite is blocking still,if not will close #90 

 there are 7 failed tests  too https://github.com/red-hat-storage/cephci/issues/90#issuecomment-627998488, i have raised another issue here for that #124

**Comment by XDsubhash** [comment]
@yogesh-mane , can you provide the logs while you tested this PR ?

**Comment by XDsubhash** [comment]
@yogesh-mane from next time pl dont send a PR and open for review without any testing.Make it a draft.

**Comment by XDsubhash** [comment]
MR typo: w/o qa

**Comment by yogesh-mane** [comment]
@XDsubhash , as I mentioned in comment 2 in issue #90 

>@XDsubhash , I didn't face commands getting stuck issue.

You can see it logs I provided in comment 2 in issue #90 

>Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/
>Logs for testcase CEPH-11255_11336_fuse: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/OSD-failure_0.log

And in our discussion in comment 5 in issue #90 

>>Because even if I add the timeout, I won't be able to test the fix because testcase would be failing for other error.
>timeout is temporary immediate fix if you need more time to fix the above 7 issues.

So I tried to give the fix , but you need to test it your environment.
Because the test run I triggered with fix couldn't verify the fix.
Test run logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589560859480/

**Pull request merged**
