### PR TITLE
 Added tier-2 nfs tests

### PR DESCRIPTION
**Pull request by yogesh-mane**
ymane@localhost.localdomain
Signed-off-by: ymane <ymane@localhost.localdomain>

Signed-off-by: ymane ymane@localhost.localdomain <ymane@redhat.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>
5.0 logs - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-6EB6VH
5.1 logs - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-0Y5997
<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>
https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574028 https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574024 https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574027 https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574003

### CODE REVIEW

**Review by hkadam134 — APPROVED** [review]
looks good to me..

**Review by AmarnatReddy — COMMENTED** [review]
S

**Review by AmarnatReddy — APPROVED** [review]
LGTM

**Review by hkadam134 — APPROVED** [review]
LGTM

**Pull request merged**
