### PR TITLE
Adding 4.x Tier1 Test Scenarios

### PR DESCRIPTION
**Pull request by hkadam134**
Adding CephFS-T1 Tests for 4.x

Signed-off-by: Hemanth <hyelloji@redhat.com>

### CODE REVIEW

**Comment by hkadam134** [comment]
Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1625809233592/

There are 2 failed Tests :-
1. Nfs ganesha is being reworked by Yogesh(https://projects.engineering.redhat.com/browse/RHCEPHQE-199), will add the TC 
 once it's ready
2. cephfs-basics is already being run on T0, its removed from the suites for T1

**Review by psathyan — COMMENTED** [review]
IMHO, it would good if we could have separate clients.

**Comment by hkadam134** [comment]
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1626162432950

**Review by psathyan — APPROVED** [review]
I appreciate the description and naming of the test case. Thanks

Looks good to me.

**Pull request merged**
