### PR TITLE
Integrates DBR scenarios into upgrade suite

### PR DESCRIPTION
**Pull request by udaysk23**
Integrates DBR scenario into upgrade suite

Signed-off-by: Uday Kurundwade <ukurundw@redhat.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by udaysk23** [comment]
Following is the log location of successful run for 5.x suite

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-NRPEAG/

**Comment by mkasturi18** [comment]
@udaysk23 , from the logs provided there is brownfield test failure due to invalid bucket name, could you please fix that in [ceph-qe-scripts](https://github.com/red-hat-storage/ceph-qe-scripts/blob/master/rgw/v2/tests/s3_swift/test_Mbuckets_with_Nobjects.py#L193) as well

**Comment by udaysk23** [comment]
> @udaysk23 , from the logs provided there is brownfield test failure due to invalid bucket name, could you please fix that in [ceph-qe-scripts](https://github.com/red-hat-storage/ceph-qe-scripts/blob/master/rgw/v2/tests/s3_swift/test_Mbuckets_with_Nobjects.py#L193) as well

Yes @mkasturi18 Doing the same

**Comment by udaysk23** [comment]
Following PR has been raised to avoid invalid bucket name failure
https://github.com/red-hat-storage/ceph-qe-scripts/pull/239

**Comment by udaysk23** [comment]
Following is the log location of successful run for 4.x suite

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-ANWXVL

**Review by psathyan — APPROVED** [review]

**Pull request merged**
