### PR TITLE
Added timeout for upstream listener pipeline

### PR DESCRIPTION
**Pull request by vivekanandan-k-rh**
# Description

Added timeout for upstream listener pipeline

### CODE REVIEW

**Review by psathyan — COMMENTED** [review]
IMO, we can have one timeout covering both the stages... what do you think?

**Comment by vivekanandan-k-rh** [comment]
Sounds good as complete execution won't take more than 30 minutes. Let update the code

**Comment by vivekanandan-k-rh** [comment]
@psathyan , Updated the code to include 30 mins of timeout for both Preparing and Staging stages together

**Review by psathyan — COMMENTED** [review]
looks good to me

**Review by sunilkumarn417 — COMMENTED** [review]
I think there are chances of file state can be in lock state with this timeout, can we add any `finally` clause.
If it is already covered then it should be good. 

Can we please check this before we merge?

**Pull request closed without merging**
