### PR TITLE
RGW multi-site: Run tests from primary and verify on secondary

### PR DESCRIPTION
**Pull request by viduship**
This yaml 'tier1_rgw_multisite_primary_to_secondary.yaml' covers the tests run on the primary site and verified on the secondary.

Signed-off-by: viduship <vimishra@redhat.com>

### CODE REVIEW

**Comment by psathyan** [comment]
Looks good to me, Kindly attach the logs... it helps build confidence with the test execution

**Comment by viduship** [comment]
> Looks good to me, Kindly attach the logs... it helps build confidence with the test execution

Sure, at the moment we are out of quota in ceph-ci and ceph-jenkins.

**Comment by viduship** [comment]
> > Looks good to me, Kindly attach the logs... it helps build confidence with the test execution
> 
> Sure, at the moment we are out of quota in ceph-ci and ceph-jenkins.

We trigger a run once the above is resolved.

**Comment by viduship** [comment]
> > > Looks good to me, Kindly attach the logs... it helps build confidence with the test execution
> > 
> > 
> > Sure, at the moment we are out of quota in ceph-ci and ceph-jenkins.
> 
> Will trigger a run once the above is resolved.

Please find the logs here -->http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-LSJKNP

**Pull request merged**
