### PR TITLE
Delete non-exist subvolume group name with force option

### PR DESCRIPTION
**Pull request by julpark-rh**
1. Create a subvolume_group name that does not exist
2. Try to remove the subvolume_group name that does not exist with force option
3. The command should fail because the subvolume_group name does not exist.
4. Check if the command is failed
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-NQB0AA
https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574169

Signed-off-by: julpark-rh <yonhyun@gmail.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by AmarnatReddy** [comment]
Script looks good to me. As suggested by hemanth..Can you add this script to suite file.

**Review by hkadam134 — CHANGES_REQUESTED** [review]
@julpark-rh - Please refer this yaml and see how the tests are added - suites/pacific/cephfs/tier-2/tier-2_cephfs_test-volume-management.yaml and follow the same for other PR's also..

**Comment by julpark-rh** [comment]
> @julpark-rh - Please refer this yaml and see how the tests are added - suites/pacific/cephfs/tier-2/tier-2_cephfs_test-volume-management.yaml and follow the same for other PR's also..

@hkadam134 I have fixed and updated it

**Comment by hkadam134** [comment]
> 

please resolve the conflicts..

**Review by hkadam134 — APPROVED** [review]
Looks Good

**Review by hkadam134 — APPROVED** [review]
Looks good

**Review by psathyan — APPROVED** [review]

**Pull request merged**
