### PR TITLE
[Automation][cephadm]Verify cephadm call

### PR DESCRIPTION
**Pull request by MohitBis**
Scenario: Verify cephadm call with command with long output

Note: Running dev shared script

### CODE REVIEW

**Comment by MohitBis** [comment]
Log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-3S86GR/

**Review by vinpapnoi — APPROVED** [review]
LGTM

**Review by sayaleeraut — APPROVED** [review]
LGTM

**Review by tintumathew10 — APPROVED** [review]
LGTM

**Pull request merged**
