### PR TITLE
upgrades from lvm 3.x latest to lvm 4.x latest

### PR DESCRIPTION
**Pull request by Ameenasuhani**
Description: upgrades from lvm 3.x latest to lvm 4.x latest

CLI used: python run.py --rhbuild 4.1-rhel-7 --global-conf conf/nautilus/upgrades/upgrade_3.x_to_4.x.yaml --osp-cred osp/osp-cred.yaml --inventory conf/inventory/rhel-7.8-server-x86_64.yaml --suite suites/nautilus/upgrades/upgrade_3.x_lvm_to_4.x_lvm.yaml --log-level info --store --ignore-latest-container

Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589360951869/

### CODE REVIEW

**Comment by rakeshgm** [comment]
@Ameenasuhani we can go ahead without adding polarion ids for rados, rbd tests or others.  let's take this in a separate PR.

**Comment by rakeshgm** [comment]
@XDsubhash are we good to merge this change ?

**Comment by XDsubhash** [comment]
@rakeshgm lgtm , was waiting for travis ci checks to pass,seems like some issue in travis-ci itself ..edited branch protection rules https://github.com/travis-ci/travis-ci/issues/10204

**Comment by XDsubhash** [comment]
@Ameenasuhani update QECI doc under helpers cli section with above cli, so it can be later added to jenkins pipeline

**Comment by Ameenasuhani** [comment]
@XDsubhash I have added  the cli to QECI doc under upgrade section please have a look.

**Pull request merged**
