### PR TITLE
Adding support for deployment of COSBench

### PR DESCRIPTION
**Pull request by psathyan**
Signed-off-by: Pragadeeswaran Sathyanarayanan <psathyan@redhat.com>

# Description

Adding support of deploying and running COSBench based on the test configuration.

__Logs__
http://magna002.ceph.redhat.com/ceph-qe-logs/psathyan/cos/

### CODE REVIEW

**Review by udaysk23 — DISMISSED** [review]
LGTM

**Review by viduship — COMMENTED** [review]
This looks good.
We can further improve by 
i ) Having multiple drivers on the same host/node on different ports.
ii) 1 driver and controller node can be colocated

**Comment by psathyan** [comment]
> This looks good. We can further improve by i ) Having multiple drivers on the same host/node on different ports. ii) 1 driver and controller node can be colocated

Pushed a new patch set that would support this scenario. Currently, we would be able to have a uniform number of drivers running in a system. 

To control locally would complicate the code. Let me know if it satisfies the requirement at hand.

**Review by viduship — DISMISSED** [review]
Looks good!

**Review by udaysk23 — APPROVED** [review]

**Pull request merged**
