### PR TITLE
closedLoop Scenario 2008402

### PR DESCRIPTION
**Pull request by rkhambad**
Signed-off-by: Rajendra Khambadkar <rkhambad@rkhambad.remote.csb>

# Description
Automate https://bugzilla.redhat.com/show_bug.cgi?id=2008402
Polarion id : CEPH-[83574413](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574413)
Test result link : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-R5QOBM/

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test

### CODE REVIEW

**Review by Ameenasuhani — COMMENTED** [review]
polarion-id: CEPH-83573679 >> points to upgrade baremetal rhcs cluster on rhel8 to rhcs 5x and cephadm adoption. As a part of the closed loop this looks more relevant to me https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574413

**Comment by Ameenasuhani** [comment]
One additional request can you remove [CEPH-83574413] from here https://github.com/red-hat-storage/cephci/blob/master/suites/pacific/upgrades/tier-1_upgrade_cephadm.yaml#L40 this will helps us with tfa analysis

**Comment by rkhambad** [comment]
Customer defect is more of a upgrade scenario from baremetal 4.x to 5.x, we are running the preflight.yaml after upgrading to 5.x. In which they are hitting issue.
considering that i marked upgrade Polarion test case (ID: CEPH-83573679).

**Comment by rkhambad** [comment]
@Ameenasuhani  have done the requested changes. 
Please review.

**Review by vdas-redhat — COMMENTED** [review]
LGTM

**Comment by Ameenasuhani** [comment]
@rkhambad As per our discussion this polarion tc https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574413 was to be added right? i don't see the changes

**Review by Ameenasuhani — APPROVED** [review]
LGTM

**Pull request merged**
