### PR TITLE
Fix cdn repos to els at 3x

### PR DESCRIPTION
**Pull request by rahullepakshi**
Fixed 3x tools repository 
test failure logs - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-GDN323/
suite suites/nautilus/upgrades/tier-2_upgrade_test-multi-path-upgrade-to-4-latest.yaml

Reference - https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/3/html-single/installation_guide_for_red_hat_enterprise_linux/index#enabling-the-red-hat-ceph-storage-repositories

Signed-off-by: rlepaksh <rlepaksh@redhat.com>

### CODE REVIEW

**Comment by psathyan** [comment]
@rahullepakshi could we move this PR to closure?

**Comment by rahullepakshi** [comment]
I initiated a run now with changes- https://ceph-downstream-jenkins-csb-storage.apps.ocp4.prod.psi.redhat.com/view/RHCS%20QE/job/rhceph-test-executor/537/console
@psathyan I will move this PR to closure ASAP

**Comment by rahullepakshi** [comment]
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-GDN323/ cron pipeline picks rhel-8 for this run though we have inventory defined as rhel-7 at https://github.com/red-hat-storage/cephci/blob/master/pipeline/scripts/cron/4/3/stage-0/test-multipath-upgrade-to-4-latest.sh

**Comment by rahullepakshi** [comment]
I need to close this PR without merging as that is Interim issue - there are 2 succesfull runs which picked "rhel-7"
https://ceph-downstream-jenkins-csb-storage.apps.ocp4.prod.psi.redhat.com/view/RHCS%20QE/job/rhceph-cron-pipeline-test-executor/80/consoleFull

https://ceph-downstream-jenkins-csb-storage.apps.ocp4.prod.psi.redhat.com/view/RHCS%20QE/job/rhceph-cron-pipeline-test-executor/72/

**Pull request closed without merging**
