### PR TITLE
[post result] Report portal launch name to have run_type and stage

### PR DESCRIPTION
**Pull request by anrao19**
Signed-off-by: Anuchaithra Rao <anrao@redhat.com>

# Description
[post result] Report portal launch name to have run_type and stage
ex: Schedule RHCEPH-5.3 - tier-2 stage-3 <launch id>
https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/all/5552
https://jenkins.ceph.redhat.com/job/rhceph-post-results/2368/console

report_portal

report_portal_email

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by tintumathew10 — COMMENTED** [review]
@anrao19 Can we get the link/screen shot from report portal to see these changes?

**Comment by anrao19** [comment]
> @anrao19 Can we get the link/screen shot from report portal to see these changes?

@tintumathew10, report potal link has been already provided in "discription", now I have updated it with screenshot

**Comment by tintumathew10** [comment]
@anrao19 , sorry I missed the link. I could see the changes in the report portal. Looks good to me.

**Review by Manohar-Murthy — APPROVED** [review]
changes are reviewed.

**Pull request merged**
