### PR TITLE
[Squid][SMB]Add smb support

### PR DESCRIPTION
**Pull request by MohitBis**
[Squid][SMB]Add smb support

- Adding smb lib support
- Adding automation support for below scenario
1. Deploy samba with auth_mode 'user' using imperative style(CLI Commands)
2. Deploy samba with auth_mode 'AD' using imperative style(CLI Commands)

### CODE REVIEW

**Comment by MohitBis** [comment]
Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-5V1M1W/

**Review by pranavprakash20 — DISMISSED** [review]
LGTM

**Comment by MohitBis** [comment]
Latest Log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-XR7YG3/

**Review by pranavprakash20 — APPROVED** [review]
Lgtm

**Review by vdas-redhat — APPROVED** [review]
LGTM

**Pull request merged**
