### PR TITLE
Add support that clones can be created without protecting snapshot via V2clone feature

### PR DESCRIPTION
**Pull request by preethisn**
Signed-off-by: Preethi Nataraj <pnataraj@localhost.localdomain>

# Description

Transparent image clones(v2) feature- Add support that clones can be created without protecting snapshot via v2clone feature

### CODE REVIEW

**Comment by preethisn** [comment]
logs are copied - http://magna002.ceph.redhat.com/ceph-qe-logs/Preethi/cephci-run-UEWTGD/

**Comment by psathyan** [comment]
Could we wait a bit on this PR? I believe we can simplify this a bit more and move towards a data driven model once we have https://github.com/red-hat-storage/cephci/pull/1323 merged.

**Comment by preethisn** [comment]
> Could we wait a bit on this PR? I believe we can simplify this a bit more and move towards a data driven model once we have #1323 merged.

---Sure. I will keep team FYI on this

**Comment by preethisn** [comment]
> > Could we wait a bit on this PR? I believe we can simplify this a bit more and move towards a data driven model once we have #1323 merged.
> 
> ---Sure. I will keep team FYI on this

**Comment by preethisn** [comment]
> With the PR merged, could you let us know your thoughts on how you would like to proceed with this PR?

I went through the 1323 PR changes, rbd_v2clone.py module has been modified. I need to create a workflow test config for this scenario and call that yaml.

**Comment by preethisn** [comment]
This PR has to be rebuilt based on the new test_rbdV2.py. So will close this and open a new one separate

**Comment by preethisn** [comment]
As per the discussions in RBD FG, We are going with old approach model until we have the new module stable Hence, request to review this PR and provide comments for taking this to closure.

**Review by Manohar-Murthy — APPROVED** [review]

**Pull request merged**
