### PR TITLE
add client using limit option

### PR DESCRIPTION
**Pull request by Ameenasuhani**
# Description
Added client daemon with limit option.
As the customer reported bug requires adding of client daemon to the existing cluster 

Customer reported bz: https://bugzilla.redhat.com/show_bug.cgi?id=1828105
Polarion: https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83573550

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs

# Checklist:

- [x] Create a test case in Polarion reviewed and approved.
- [x] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [x] Review the automation design
- [x] Implement the test script and perform test runs
- [x] Submit PR for code review and approve
- [x] Update Polarin Test with Automation script details and update automation fields
- [x] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test

Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1600871881932/result.html

### CODE REVIEW

**Review by sunilkumarn417 — CHANGES_REQUESTED** [review]
- Please add these changes in containerized test suite.
- Try roll over with multiple clients.
- Is it supported on 3.x luminous? if yes please add respective code changes in luminous suites.

**Comment by rakeshgm** [comment]
Have you completed the checklist actions. Pls update the check list.

**Comment by Ameenasuhani** [comment]
@sunilkumarn417 I have added the changes to luminous and nautilus both in rpm and container.
Also, to add multiple clients we might have to add a repetitive test module of roll_over and rerun. 

Logs:
RHCS3:
Sanity_containerized_ceph_ansible : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1600952700833/result.html

RHCS4:
Sanity_containerized_ceph_ansible: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1600967610870/result.html

**Review by sunilkumarn417 — APPROVED** [review]
LGTM

**Comment by rakeshgm** [comment]
@Ameenasuhani please take up this issue for the next PR https://github.com/red-hat-storage/cephci/issues/224

**Comment by Ameenasuhani** [comment]
@rakeshgm sure will work on it

**Pull request merged**
