### PR TITLE
Clone scale automation changes for compatibility on Baremetal

### PR DESCRIPTION
**Pull request by sumabai**
# Automation had to undergo IO config changes to be executed on Baremetal configuration,

Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-HL6T7E/Clone_scale_testing_0.log

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by hkadam134 — APPROVED** [review]
LGTM

**Comment by AmarnatReddy** [comment]
Hi Suma,

Can you add the sample suite file test case in description?
So that it will easy for knowing the supported options

Regards,
Amarnath

**Comment by sumabai** [comment]
> Hi Suma,
> 
> Can you add the sample suite file test case in description? So that it will easy for knowing the supported options
> 
> Regards, Amarnath

Added required details, plz review

**Review by AmarnatReddy — APPROVED** [review]
LGTM

**Pull request merged**
