### PR TITLE
CEPH-10312: Test to verify MAX_AVAIL value is correctly updated in ceph df upon addition of an OSD with 0 weight

### PR DESCRIPTION
**Pull request by harshkumarRH**
[CEPH-10312](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-10312): Tier-4 test case to verify the change in MAX_AVAIL attribute in ceph df stats. 
MAX_AVAIL value should decrease/increases depending on the weight of the newly added OSD and should not become 0 or any other invalid value

**Test Suites added -**
- suites/pacific/rados/tier-4_rados_tests.yaml
- suites/quincy/rados/tier-4_rados_tests.yaml

**Tests added/modified -**
- tests/rados/pool_tests.py
- tests/rados/test_cephdf.py

**Test modules modified -**
_def add_ in _ceph/ceph_admin/add.py_
_set_osd_in_ in _ceph/rados/utils.py_

**Steps -**
1. Create a pool with default pg number
2. Create 'n' number of objects using rados put(perform IOPS)
3. Capture ceph df stats and remove the last osd from the cluster osd list
4. Set the param 'osd_crush_initial_weight' to 0
5. Add the removed osd
6. Verify that the weight of the added osd is 0 using ceph osd tree
7. Capture ceph df stats, MAX AVAIL should decrease by
the size of the concerned osd and should not change to 0
8. Re-weight the OSD to its initial value
9. Capture ceph df stats, MAX AVAIL should be same as
initial value and not equal to 0 or decreased value

**Logs -**
RHCS 5.3 - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-WKV3KE/
RHCS 6.0 - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-3YMAKV/

Signed-off-by: Harsh Kumar <hakumar@redhat.com>

### CODE REVIEW

**Comment by harshkumarRH** [comment]
Adding DNM tag as the changes need additional review

**Comment by harshkumarRH** [comment]
Conflicts have been resolved with latest commits, adding ready-for-review tag

**Review by pdhiran — COMMENTED** [review]
Looks good to merge. If no other comments, will have this merged by EOD.

**Comment by neha-gangadhar** [comment]
Looks good

**Comment by neha-gangadhar** [comment]
Already 2 reviews completed, if no conflicts can be moved to merge.

**Review by tintumathew10 — APPROVED** [review]
Looks good

**Pull request merged**
