### PR TITLE
Validating kernel mount options for FS

### PR DESCRIPTION
**Pull request by AmarnatReddy**
Validating kernel mount options for FS
We are validating all the basic options present for kernel mount

https://docs.ceph.com/en/quincy/man/8/mount.ceph/
Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-OQXHOM/ 

Complete Tier-1 log : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-PEBCL1/

Signed-off-by: Amarnath K <amk@amk.remote.csb>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by hkadam134 — COMMENTED** [review]
* Can we validate the values set ?
* Verify the timeout validation

**Comment by yogesh-mane** [comment]
Hi @AmarnatReddy , could we add soe IO's for each mount.

**Comment by AmarnatReddy** [comment]
Updated all the comments
Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-LWDH0O/

**Review by hkadam134 — APPROVED** [review]
Looks Goot to me.

**Pull request merged**
