### PR TITLE
Bucket notifications on archive zone with ObjectSync:Create/Delete events

### PR DESCRIPTION
**Pull request by viduship**
# Description
Bucket notifications on archive zone with ObjectSync:create event
[CEPH-83575922](https://polarion.engineering.redhat.com/polarion/redirect/project/CEPH/workitem/question_mark/id=CEPH-83575922)

Pass logs for bucket notification with archive zone :
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-QQCCFE

Dependent ceph-qe-scripts pr https://github.com/red-hat-storage/ceph-qe-scripts/pull/614/files
Ticket https://issues.redhat.com/browse/RHCEPHQE-14898

TFA: Pass logs for LC sized-based filter tests that fail in the existing order, but have passed after running post the notification tests:
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-3WK9HP

### CODE REVIEW

**Review by hmaheswa — COMMENTED** [review]
@viduship 
please add tests for object put and delete on arc site

**Comment by viduship** [comment]
> @viduship please add tests for object put and delete on arc site

Done

**Review by hmaheswa — APPROVED** [review]
LGTM

**Review by anrao19 — APPROVED** [review]
LGTM

**Review by ckulal — APPROVED** [review]

**Pull request merged**
