### PR TITLE
Adding FS TC 83574327

### PR DESCRIPTION
**Pull request by julpark-rh**
https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574327

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-4VG5Z6

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by hkadam134** [comment]
@julpark-rh - Can you please include IOs after every client's permission change and validate the permissions?

**Review by hkadam134 — COMMENTED** [review]
Please add IOs

**Comment by julpark-rh** [comment]
> Please add IOs

i have some concerns.. lets discuss about it soon

**Comment by julpark-rh** [comment]
https://github.com/red-hat-storage/cephci/pull/2551

**Pull request closed without merging**
