### PR TITLE
[LibFix] Fix bootstrap workflow to support IBM build

### PR DESCRIPTION
**Pull request by vamahaja**

### CODE REVIEW

**Review by MohitBis — APPROVED** [review]
LGTM

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by MohitBis — COMMENTED** [review]
Need to add repo with x86 not .repo

**Review by MohitBis — CHANGES_REQUESTED** [review]
Need to pass repo with x86_64 not .repo

**Review by tintumathew10 — APPROVED** [review]
lgtm

**Review by vdas-redhat — APPROVED** [review]
LGTM

**Review by MohitBis — APPROVED** [review]
LGTM

**Pull request merged**
