### PR TITLE
Fixes for tier-2_fs suite failures in CI runs

### PR DESCRIPTION
**Pull request by sumabai**
# Description

concurrent clone test: it was failing as clones were not created in parallel, so expected status max concurrent=2, was not seen. Added code to create in parallel.
mds_service_add_removal_test,mon_service_add_removal_test: cleanup failures due to non-empty subvol directories was seen, this was due to improper cleanup handling in test_clone_threads.py, fixed cleanup code in this script.

Logs with fix: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-CUYPQL/

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by neha-gangadhar** [comment]
LGTM

**Comment by sumabai** [comment]
> LGTM. Minor comment: We have removed folio from BM pool. Please remove the conf file from PR. cc: @AmarnatReddy

baremetal_pipeline directory was not reqd, have removed it.

**Comment by sumabai** [comment]
> Hi @sumabai Lately i am realising [tests/cephfs/snapshot_clone/clone_threads.py](https://github.com/red-hat-storage/cephci/blob/master/tests/cephfs/snapshot_clone/clone_threads.py) and the above test case cover the same scenario. If you feel same can we remove this from tier_2-fs.yaml
> 
> Regards, Amarnath

Hi Amar,
The test posted for review is test_clone_threads.py

> Hi @sumabai Lately i am realising [tests/cephfs/snapshot_clone/clone_threads.py](https://github.com/red-hat-storage/cephci/blob/master/tests/cephfs/snapshot_clone/clone_threads.py) and the above test case cover the same scenario. If you feel same can we remove this from tier_2-fs.yaml
> 
> Regards, Amarnath

Yes Amar, both cephfs/snapshot_clone/clone_threads.py and cephfs/test_clone_threads.py perform same workflow. But i have added fixes to test_clone_threads.py which is required to avoid script failures in CI runs. So, i'll retain test_clone_threads.py and look for clone_threads.py included test suite and remove it.

**Comment by sumabai** [comment]
> Hi @sumabai Lately i am realising [tests/cephfs/snapshot_clone/clone_threads.py](https://github.com/red-hat-storage/cephci/blob/master/tests/cephfs/snapshot_clone/clone_threads.py) and the above test case cover the same scenario. If you feel same can we remove this from tier_2-fs.yaml
> 
> Regards, Amarnath

I have made required changes Amar, added parallel clone create fixes to clone_threads.py, removed test_clone_threads.py from tier-2_fs

**Review by AmarnatReddy — APPROVED** [review]
LGTM

**Pull request merged**
