### PR TITLE
New Automation,TFA fixes,Crash check

### PR DESCRIPTION
**Pull request by sumabai**
# Description

Jira tasks:
TFA issues : https://issues.redhat.com/browse/RHCEPHQE-14440

Automation : https://issues.redhat.com/browse/RHCEPHQE-14296
Added automation for,
Workflow5 - Validate quiesce release response when quiesce-timeout and quiesce-expire time is reached.
Workflow6 - Perform all state transitions and validate response

Also added small module to fs_utils_v1 to get crash ls-new output to validate health of cluster after testing.

Logs:
Workflow6:  http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-BEJCI0
Workflow5: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-K9029A

TFA fixes:
Workflow_1: 
Latest log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-YQG2MK (Cleanup failure due to other subvolumes in same subvolumegroup)
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-ZDF0ZV/cg_snap_test_0.log

Cg quiesce systemic suite:
TFA issue and fix - thread kill was attempted in incorrect way, this code has got checked in unintentionally while exploring thread kill possibilities. Addressed it, by removing invalid code and adding wait time to let IO complete.

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by neha-gangadhar** [comment]
@sumabai The test log attached has failures. Please check.

**Comment by sumabai** [comment]
> @sumabai The test log attached has failures. Please check.

Hi Neha,
The Failure is in workflow1 log in cleanup as below,

2024-05-10 17:57:36,427 (cephci.snapshot_clone.cg_snap_test) [INFO] - cephci.ceph.ceph.py:1563 - Running command ceph fs subvolume rm cephfs sv_def_3_2 on 10.0.208.238 timeout 600
2024-05-10 17:57:37,151 (cephci.snapshot_clone.cg_snap_test) [ERROR] - cephci.ceph.ceph.py:1599 - Error 39 during cmd, timeout 600
2024-05-10 17:57:37,153 (cephci.snapshot_clone.cg_snap_test) [ERROR] - cephci.ceph.ceph.py:1600 - Error ENOTEMPTY: subvolume 'sv_def_3_2' has snapshots

I do have code to delete snapshots created during test here,

2024-05-10 17:37:12,539 (cephci.snapshot_clone.cg_snap_test) [INFO] - cephci.ceph.ceph.py:1563 - Running command ceph fs subvolume snapshot rm cephfs sv_def_3_2 cg_snap_p4b on 10.0.208.238 timeout 600
2024-05-10 17:37:13,356 (cephci.snapshot_clone.cg_snap_test) [INFO] - cephci.ceph.ceph.py:1597 - Command completed successfully

The snapshots created with current test are all deleted. The snapshots leftover that caused subvolume remove failure in cleanup are the ones from previous tests on same subvolumes. I had been repeated tests multiple times on same subvolumes, and while script was failing before it may have skipped snapshot deletion.

**Comment by sumabai** [comment]
> > @sumabai The test log attached has failures. Please check.
> 
> Hi Neha, The Failure is in workflow1 log in cleanup as below,
> 
> 2024-05-10 17:57:36,427 (cephci.snapshot_clone.cg_snap_test) [INFO] - cephci.ceph.ceph.py:1563 - Running command ceph fs subvolume rm cephfs sv_def_3_2 on 10.0.208.238 timeout 600 2024-05-10 17:57:37,151 (cephci.snapshot_clone.cg_snap_test) [ERROR] - cephci.ceph.ceph.py:1599 - Error 39 during cmd, timeout 600 2024-05-10 17:57:37,153 (cephci.snapshot_clone.cg_snap_test) [ERROR] - cephci.ceph.ceph.py:1600 - Error ENOTEMPTY: subvolume 'sv_def_3_2' has snapshots
> 
> I do have code to delete snapshots created during test here,
> 
> 2024-05-10 17:37:12,539 (cephci.snapshot_clone.cg_snap_test) [INFO] - cephci.ceph.ceph.py:1563 - Running command ceph fs subvolume snapshot rm cephfs sv_def_3_2 cg_snap_p4b on 10.0.208.238 timeout 600 2024-05-10 17:37:13,356 (cephci.snapshot_clone.cg_snap_test) [INFO] - cephci.ceph.ceph.py:1597 - Command completed successfully
> 
> The snapshots created with current test are all deleted. The snapshots leftover that caused subvolume remove failure in cleanup are the ones from previous tests on same subvolumes. I had been repeated tests multiple times on same subvolumes, and while script was failing before it may have skipped snapshot deletion.

Latest run passed log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-UAR47Z

**Review by AmarnatReddy — APPROVED** [review]
LGTM

**Pull request merged**
