### PR TITLE
adding rhcs_qe_sdk code to cephci

### PR DESCRIPTION
**Pull request by hmaheswa**
Signed-off-by: Hemanth Maheswarla <hmaheswa@hmaheswa.remote.csb>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by psathyan** [comment]
@HaruChebrolu @hmaheswa please create a separate branch. Kindly don't merge this into the master branch as we have move work to complete before it is fully ready.

**Comment by chebroluharika** [comment]
@hmaheswa Please create PR for qesdk_to_cephci branch which was already created for cephci also.

**Comment by HaruChebrolu** [comment]
@hmaheswa 
Please raise an PR for qesdk_to_cephci which was already created in cephci.

**Comment by hmaheswa** [comment]
Okay @psathyan and @HaruChebrolu  I will close this PR and raise a new PR for qesdk_to_cephci

**Pull request closed without merging**
