### PR TITLE
CephFS Customer Case BZ Automation

### PR DESCRIPTION
**Pull request by hkadam134**
# Description

Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-CRS24M/
Polarion ID : [CEPH-83586294 - Ensure there are no reports of oversized cache warnings from MDS](https://polarion.engineering.redhat.com/polarion/redirect/project/CEPH/workitem?id=CEPH-83586294)

This has to go into the baremetal suite.

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Review by sumabai — DISMISSED** [review]
lgtm

**Comment by neha-gangadhar** [comment]
@hkadam134 How are we ensuring the test runs on Baremetal systems? Are you planning to add a different suite file?

**Comment by hkadam134** [comment]
> @hkadam134 How are we ensuring the test runs on Baremetal systems? Are you planning to add a different suite file?

Yes, Was discussing the same with Amar. I do have a file created - "tier-3_cephfs_bugs_baremetal.yaml" locally.
Planning to add that file too that and update the baremetal yaml.

**Review by neha-gangadhar — APPROVED** [review]
Approved

**Pull request merged**
