### PR TITLE
TFA FIX- Scheduled scrub and Inconsistent object in EC pool

### PR DESCRIPTION
**Pull request by SrinivasaBharath**
# Description

Jira Tickets:
    1. https://issues.redhat.com/browse/RHCEPHQE-15248
    2. https://issues.redhat.com/browse/RHCEPHQE-15398

1. The issue with the existing code is -
set begin_hour > end_hour and current_time > end_hour     Expected behavior- scrubbing should begin within the interval specified
           
2. In the automation script, I was checking the wrong place, and I modified the code.
begin_hour > end_hour 
                 Expected behavior- scrubbing should not start in this time period
                 Actual behavior - The scrubbing is getting started 

          Log - 1. http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-N5381Y
                    2. http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-TL67H1/

3. Previously I was not checking scrub and deep-scrub scenarios, I included the logic that the script verifies scrub and deep-scrub functionality.

4. Failure cases-
Each test case first checks the scrub scenario if it passes then executes the deep-scrub scenario. so

                      The maximum wait time for the failure case is 2 hours during the deep-scrub checking.
                       The minimum time for the failure is less than an hour during the scrub checking.
                       The maximum time to the negative scenarios is two hours this includes both scrub and deep-scrub functionality checks.

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by SrinivasaBharath** [comment]
Squid Log - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-DSU3DD

**Comment by SrinivasaBharath** [comment]
Scub and deep-scrub on  inconsistent objects in EC pool test case log - 
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-98BJVK

**Comment by SrinivasaBharath** [comment]
Re-opening the PR

**Comment by SrinivasaBharath** [comment]
Re-opening the PR

**Comment by SrinivasaBharath** [comment]
Please find the pass logs-
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-ZT0TFU
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-BMED3Z
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-9NPVP2 - Full suite

**Comment by pdhiran** [comment]
@SrinivasaBharath , Ronen has replied on the bugzilla, saying that the behaviour looks to be as expected.

``` This seems to be the desired behavior.
If the allowed times are, for example, 17:00 to 04:00, scrubs are allowed at 19:00 ```

https://bugzilla.redhat.com/show_bug.cgi?id=2308444#c2 


Can you please check the comments, and modify code/ polarion as expected?

We will merge the PR once it's fixed.

**Comment by SrinivasaBharath** [comment]
Test case pass log- http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-KTZKBF

**Comment by SrinivasaBharath** [comment]
Logs- 
1. Reef - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-4K6PVU/
2. Reef - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-2WI1K5/
3. Squid - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-4XMHAY/

**Review by pdhiran — APPROVED** [review]
Looks good.

**Pull request merged**
