### PR TITLE
[Lib] Add libraries to setup user & ceph SSH keys

### PR DESCRIPTION
**Pull request by vamahaja**
Add below classes to setup user and ceph SSH keys

- class SetUpSSHKeys - Generates root & ceph-user SSH keys and copy to different nodes.
- class CopyCephSshKeyToHost - Copy ceph SSH key to nodes.

Signed-off-by: Vaibhav Mahajan <vamahaja@redhat.com>

### CODE REVIEW

**Review by MohitBis — APPROVED** [review]
LGTM

**Comment by pranavprakash20** [comment]
Log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-mnkh2/

**Comment by vamahaja** [comment]
This PR is part of https://github.com/red-hat-storage/cephci/pull/2131. Refer https://github.com/red-hat-storage/cephci/pull/2131#issuecomment-1420229223 for test run

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Pull request merged**
