### PR TITLE
reduce the disk-size to 10g

### PR DESCRIPTION
**Pull request by rakeshgm**
there is huge osd_disk size added without actually utilising the entire usage. I have reduced the sizes to 10G. 

Signed-off-by: rakeshgm <rakeshgm@redhat.com>

### CODE REVIEW

**Comment by rakeshgm** [comment]
the storage used under nautilus should be approx. 1.2Tb, with the reduces disk size, the storage should be around 700Gb. will do a sanity run and check.

**Comment by sunilkumarn417** [comment]
Requested DMFG team to execute their test suites using `reduced_osd_size` branch code changes

**Comment by sunilangadi2** [comment]
@rakeshgm @sunilkumarn417 When i tried this CI run on this branch **reduced_osd_size**
python run.py --rhbuild 4.2-rhel-7 --global-conf conf/nautilus/dashboard/sanity-dashboard.yaml --osp-cred osp/osp-cred-ci-2.yaml --inventory conf/inventory/rhel-7.8-server-x86_64.yaml --suite suites/nautilus/dashboard/sanity_containerized_ceph_dashboard.yaml --log-level info --ignore-latest-container --rhs-ceph-repo http://download.eng.bos.redhat.com/rhel-7/composes/raw/ceph-4.2-rhel-7/latest-RHCEPH-4-RHEL-7/
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1603780468878/result.html
Since reduced the osd disk size to 10G after some of the I/O tests cluster is getting filled and osd's went down 
and the cluster is no longer useful for further testing and some of the daemon got crashed.
Provided dashboard url : http://10.0.101.193:8443/#/dashboard
admin/p@ssw0rd
So my opinion is not to decrease osd disk size.

**Comment by rakeshgm** [comment]
will reopen this when there is more info.

**Pull request closed without merging**
