### PR TITLE
CrushtoolWorkflows.py: Addressing minor comments and moving to tier-4

### PR DESCRIPTION
**Pull request by pdhiran**
Addressed following comments:
1. Move the method ` check_file_exists_on_client ` under CoreWorkflows.
2. Moved the test to tier-4 Suite.
3. Updated the default location for file creation.

### CODE REVIEW

**Comment by neha-gangadhar** [comment]
Looks good to me.

**Comment by harshkumarRH** [comment]
LGTM

**Comment by pdhiran** [comment]
@neha-gangadhar , @harshkumarRH , Can one of you approve the PR?

**Review by neha-gangadhar — APPROVED** [review]

**Comment by neha-gangadhar** [comment]
@pdhiran  Done

**Pull request merged**
