### PR TITLE
Adding upstream Rados regression suite files.

### PR DESCRIPTION
**Pull request by SrinivasaBharath**
# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [x] Implement the test script and perform test runs
- [x] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by SrinivasaBharath** [comment]
Log files- 
              1. Regression test - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-4V56UO
              2. Stretch cluster log-  http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-3TF0RY

In the regression tests, a test case failed with an error "PG's not reduced after bulk flag disabled". This is not a script error. An investigation is in progress.

**Review by tintumathew10 — COMMENTED** [review]
LGTM

**Comment by TejasC88** [comment]
Request to analyze failure and provide complete pass log.

**Comment by SrinivasaBharath** [comment]
Discussed with the FG team and raised a  tracker for the Pg autoscaler bulk flag test case failure.
I removed the test case from the regression tests. Once we get the fix I will include the test case in the regression suite. 

Tracker details- https://github.com/red-hat-storage/cephci/issues/2002

**Review by sunilkumarn417 — APPROVED** [review]
LGTM.

Since there is tracker, we could merge this suites in execution.

**Pull request merged**
