### PR TITLE
[Nfs] Add HA support for NFS

### PR DESCRIPTION
**Pull request by pranavprakash20**
# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by pranavprakash20** [comment]
Run log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-75YGRM/

**Comment by pranavprakash20** [comment]
suite file is not attached, as the test will be added as part of baremetal setup because of the vip required. In rhosd the vip assigned initially might not hold good in the later runs, hence its good to run the ha tests in baremetal setup with dedicated vip's.

For testing a vip was hardcoded

```
  - test:
      name: Nfs Cluster creation with HA
      module: nfs_verify_nfs_ha.py
      desc: Test NFS cluster creation with HA
      polarion-id:
      abort-on-fail: false
      config:
        nfs_version: 4.1
        clients: 3
        servers: 2
        ha: True
        vip: 10.0.210.1/22 
```

**Review by MohitBis — APPROVED** [review]
LGTM

**Comment by pranavprakash20** [comment]
run logs:  http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-6QHCYZ/
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-F5Y34A/

**Review by msainiRedhat — APPROVED** [review]
LGTM

**Review by vdas-redhat — APPROVED** [review]
LGTM

**Pull request merged**
