### PR TITLE
[Test] Add test to validate nfs ganesha multi node deployment

### PR DESCRIPTION
**Pull request by pranavprakash20**
# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by pranavprakash20** [comment]
run log: https://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-VDL3SF/

**Review by MohitBis — DISMISSED** [review]
LGTM

**Review by msainiRedhat — DISMISSED** [review]
LGTM

**Review by MohitBis — DISMISSED** [review]
LGTM

**Review by msainiRedhat — APPROVED** [review]
LGTM

**Comment by pranavprakash20** [comment]
DNM.

**Review by msainiRedhat — DISMISSED** [review]
LGTM

**Review by MohitBis — APPROVED** [review]
LGTM

**Review by vamahaja — DISMISSED** [review]

**Review by MohitBis — APPROVED** [review]
LGTM

**Review by vamahaja — APPROVED** [review]

**Pull request merged**
