### PR TITLE
[rm-cluster] Add validation for log directory removal

### PR DESCRIPTION
**Pull request by vinpapnoi**

### CODE REVIEW

**Comment by vinpapnoi** [comment]
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-T17K9T

Test run with the changes.

**Review by pranavprakash20 — DISMISSED** [review]
LGTM

**Review by vamahaja — COMMENTED** [review]
LGTM

**Review by tintumathew10 — COMMENTED** [review]
LGTM

**Review by pranavprakash20 — APPROVED** [review]
Lgtm

**Review by vamahaja — APPROVED** [review]

**Pull request merged**
