### PR TITLE
Adding Reef suites and conf files

### PR DESCRIPTION
**Pull request by AmarnatReddy**
# Description
Adding Reef suites and conf files

Moving suites and conf files to reef folder

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

### CODE REVIEW

**Comment by neha-gangadhar** [comment]
@AmarnatReddy Can you please share the updated reef metadata file link as well here in comment for review?

**Comment by AmarnatReddy** [comment]
> @AmarnatReddy Can you please share the updated reef metadata file link as well here in comment for review?

MR : https://gitlab.cee.redhat.com/rhcs-qe/cephqe-jenkins/-/merge_requests/249

**Comment by neha-gangadhar** [comment]
@AmarnatReddy Looks good. Can we remove stale conf and suite files from pacific and quincy folders if not currently being used anywhere? eg of conf files : tier-2_cephfs_mds_pinning.yaml and tier-3_non_collocated.yaml

**Comment by AmarnatReddy** [comment]
> @AmarnatReddy Looks good. Can we remove stale conf and suite files from pacific and quincy folders if not currently being used anywhere? eg of conf files : tier-2_cephfs_mds_pinning.yaml and tier-3_non_collocated.yaml

Can I take it up in new PR, As this is only concentrated on adding reef suites and confs

**Review by neha-gangadhar — APPROVED** [review]
lgtm

**Pull request merged**
